# This file requires the MariaDB operator - https://github.com/mariadb-operator/mariadb-operator 
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.db.host }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "romm" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  storage:
    size: 3Gi
  replicas: {{ .Values.db.replicas | default 1}}
  resources:
  {{- toYaml .Values.db.resources | nindent 4 }}
  livenessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  startupProbe:
    failureThreshold: 10
    periodSeconds: 5
    timeoutSeconds: 5
  service:
    type: ClusterIP
    sessionAffinity: None
  tls:
    enabled: true
    serverCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
    clientCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ .Values.db.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "romm" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  name: {{ .Values.db.name }}
  mariaDbRef:
    name: {{ .Values.db.host }}
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Values.db.user }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "romm" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  name: {{ .Values.db.user }}
  mariaDbRef:
    name: {{ .Values.db.host }}
  passwordSecretKeyRef:
    name: {{ .Release.Name }}-secret
    key: DB_PASSWD
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ .Values.db.host }}-user-grant
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "romm" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  mariaDbRef:
    name: {{ .Values.db.host }}
  privileges:
    - "ALL"
  database: {{ .Values.db.name }}
  table: "*"
  username: {{ .Values.db.user }}
  host: "%"
  grantOption: false
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
