apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "romm" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  DB_HOST: "{{ .Values.db.host }}"
  DB_NAME: "{{ .Values.db.name }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_SSL_CA: "{{ .Values.db.sslCa }}"
  DB_USER: "{{ .Values.db.user }}"
  DISABLE_RUFFLE_RS: "true"
  DISABLE_USERPASS_LOGIN: "true"
  ENABLE_SCHEDULED_RESCAN: "true"
  OIDC_ENABLED: "true"
  OIDC_PROVIDER: "Authelia"
  OIDC_REDIRECT_URI: "{{ .Values.app.oidc.redirectUri }}"
  OIDC_SERVER_APPLICATION_URL: "{{ .Values.app.oidc.serverApplicationUrl }}"
  OIDC_TLS_CACERTFILE: "{{ .Values.app.oidc.tlsCaCertFile }}"
  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "{{ .Values.redis.port }}"
  ROMM_BASE_URL: "https://{{ .Values.network.baseUrl }}"
  ROMM_DB_DRIVER: "{{ .Values.app.dbDriver }}"
  SCHEDULED_RESCAN_CRON: "0 5 * * *"
  HASHEOUS_API_ENABLED: "true"
