apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print .Release.Name "-env" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
    DNS_SERVER_DOMAIN: "{{ .Values.config.dnsServerDomain }}"