# -- Base domain used for the services
domain:

external:
  # -- External URL used to access the services
  url:

services:
  service1:
    # -- Port the service listens on
    port: 
    # -- Protocol/scheme used to access the service (e.g. http, https)
    scheme: 
    middleware:
      # -- Enable authentication middleware for the service
      auth: 
    external:
      # -- External IP address of the service
      ip: 
  service2:
    port:
    scheme:
    middleware:
      auth:
    external:
      ip: