apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-server-cert
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  secretName: grafana-server-cert
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  commonName: grafana.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
    - "grafana.{{ .Release.Namespace }}.svc.cluster.local"
    - "grafana.{{ .Release.Namespace }}.svc"
    - "grafana.{{ .Release.Namespace }}"
    - "grafana"
    - "localhost"