apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: imports
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: Imports