apiVersion: v1
kind: Secret
metadata:
  name: "grafana-admin-credentials"
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: {{ .Values.config.admin.user | quote }}
    GF_SECURITY_ADMIN_PASSWORD: {{ .Values.config.admin.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
    MYSQL_PASSWORD: {{ .Values.database.password | quote }}
    OIDC_CLIENT_ID: {{ .Values.config.oidc.clientId | quote }}
    OIDC_CLIENT_SECRET: {{ .Values.config.oidc.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-contactpoint-secret" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  alert-mails: {{ .Values.config.contactpoint.mailAddress | quote }}