{{ include "cnpg.resources" (dict "root" $ "vals" .Values.mainDb) }}
---
# include "baseResources.httproute" (dict "root" $ "vals" .Values.app) }}
---
# include "baseResources.service" (dict "root" $ "vals" .Values.app) }}