# This file requires the MariaDB operator - https://github.com/mariadb-operator/mariadb-operator 
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.mariadb.host }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  storage:
    size: 3Gi
  replicas: {{ .Values.mariadb.replicaCount | default 1}}
  resources:
  {{- toYaml .Values.mariadb.resources | nindent 4 }}
  livenessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  startupProbe:
    failureThreshold: 10
    periodSeconds: 5
    timeoutSeconds: 5
  service:
    type: ClusterIP
    sessionAffinity: None
  tls:
    enabled: true
    serverCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer