# This file requires the MariaDB operator - https://github.com/mariadb-operator/mariadb-operator 
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: db-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "bookstack" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  storage:
    size: 3Gi
  replicas: {{ .Values.db.replicas | default 1 }}
  resources:
  {{- toYaml .Values.db.resources | nindent 4 }}
  livenessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  startupProbe:
    failureThreshold: 10
    periodSeconds: 5
    timeoutSeconds: 5
  service:
    type: ClusterIP
    sessionAffinity: None
  tls:
    enabled: true
    required: true
    serverCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
    clientCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "bookstack" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  name: {{ .Release.Name }}-db
  mariaDbRef:
    name: db-{{ .Release.Name }}
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Release.Name }}-user
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "bookstack" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  name: {{ .Release.Name }}-user
  mariaDbRef:
    name: db-{{ .Release.Name }}
  passwordSecretKeyRef:
    name: {{ .Release.Name }}-secret
    key: DB_PASSWORD
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ .Release.Name }}-user-grant
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "bookstack" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  mariaDbRef:
    name: db-{{ .Release.Name }}
  privileges:
    - "ALL"
  database: {{ .Release.Name }}-db
  table: "*"
  username: {{ .Release.Name }}-user
  host: "%"
  grantOption: false
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
