apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  DB_QUERY_JSON: '{"ssl": "true"}'
  DISABLE_RUFFLE_RS: "true"
  DISABLE_USERPASS_LOGIN: "true"
  ENABLE_SCHEDULED_RESCAN: "true"
  OIDC_ENABLED: "true"
  OIDC_AUTOLOGIN: "true"
  OIDC_PROVIDER: "Authelia"
  REDIS_HOST: {{ include "redis.serviceFQDN" (dict "root" $) | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  ROMM_BASE_URL: {{ printf "https://%s" .Values.app.route.baseUrl | quote }}
  ROMM_DB_DRIVER: {{ .Values.database.type | quote }}
  SCHEDULED_RESCAN_CRON: "0 5 * * *"
  HASHEOUS_API_ENABLED: "true"
  HLTB_API_ENABLED: "true"
  ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: "true"
  LOGLEVEL: "WARNING"