{{ include "baseResources.service" (dict "root" $ "vals" .Values.app) }}
---
{{ include "baseResources.httproute" (dict "root" $ "vals" .Values.app) }}
---
{{ include "redis.resources" (dict "root" $ "vals" .Values.redis) }}
---
{{ include "mariadb.resources" (dict "root" $ "vals" .Values.database) }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component | quote }}
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      app.kubernetes.io/component: {{ .component | quote }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component | quote }}

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        fsGroup: {{ printf "%d" (int64 .gid) }}

      initContainers:
        {{- include "baseResources.waitForMariadb" $.Values.database | nindent 8 }}
        {{- include "baseResources.waitForNfs" (dict "volumeName" "games") | nindent 8 }}
        {{- include "baseResources.waitForRedis" (dict
            "host" (include "redis.serviceFQDN" (dict "root" $))
            "password" $.Values.redis.password) | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name | quote }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name | quote }}
{{- end }}

          volumeMounts:
            - name: assets
              mountPath: /romm/assets
            - name: games
              mountPath: /romm/library
            - name: resources
              mountPath: /romm/resources
            - name: config
              mountPath: /romm/config
            - name: authelia-fullchain
              mountPath: {{ .Values.config.oidc.tlsCaCertFile | quote }}
              subPath: {{ .Values.config.oidc.tlsCaCertFile | base | quote }}

      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: {{ printf "%s-assets" .Release.Name | quote }}
        - name: games
          nfs:
            server: {{ .Values.storage.nfs.server | quote }}
            path: {{ .Values.storage.nfs.path | quote }}
        - name: resources
          persistentVolumeClaim:
            claimName: {{ printf "%s-resources" .Release.Name | quote }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ printf "%s-config" .Release.Name | quote }}
        - name: authelia-fullchain
          configMap:
            name: authelia-fullchain
            items:
              - key: {{ base .Values.config.oidc.tlsCaCertFile | quote }}
                path: {{ base .Values.config.oidc.tlsCaCertFile | quote }}