{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        fsGroup: {{ printf "%d" (int64 .gid) }}

      initContainers:
        {{- include "baseResources.waitForMariadb" $.Values.database | nindent 8 }}

        {{- include "baseResources.waitForSamba" $.Values.storage.smb | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          ports:
            {{- range .service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}
{{- end }}

          volumeMounts:
            - name: assets
              mountPath: /romm/assets
            - name: games
              mountPath: /romm/library
            - name: resources
              mountPath: /romm/resources
            - name: config
              mountPath: /romm/config
            - name: authelia-fullchain
              mountPath: "{{ .Values.config.oidc.tlsCaCertFile }}"
              subPath: "{{ .Values.config.oidc.tlsCaCertFile | base }}"

      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: {{ printf "%s-assets" .Release.Name }}
        - name: games
          persistentVolumeClaim:
            claimName: {{ printf "%s-games" .Release.Name }}
        - name: resources
          persistentVolumeClaim:
            claimName: {{ printf "%s-resources" .Release.Name }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ printf "%s-config" .Release.Name }}
        - name: authelia-fullchain
          configMap:
            name: authelia-fullchain
            items:
              - key: "{{ .Values.config.oidc.tlsCaCertFile | base }}"
                path: "{{ .Values.config.oidc.tlsCaCertFile | base }}"