apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.database }}
  DB_HOST: {{ .host | quote }}
  DB_NAME: {{ .name | quote }}
  DB_PORT: {{ .port | quote }}
  DB_USER: {{ .username | quote }}
  DB_PASSWD: {{ .password | quote }}
  {{- end }}

  REDIS_PASSWORD: {{ .Values.redis.password | quote }}

  {{- with .Values.config }}
  {{- with .oidc }}
  OIDC_CLIENT_ID: {{ .clientId | quote }} 
  OIDC_CLIENT_SECRET: {{ .clientSecret | quote }}
  OIDC_REDIRECT_URI: {{ .redirectUri | quote }}
  OIDC_SERVER_APPLICATION_URL: {{ .serverApplicationUrl | quote }}
  OIDC_TLS_CACERTFILE: {{ .tlsCaCertFile | quote }}
  {{- end }}

  IGDB_CLIENT_ID: {{ .igdb.clientId | quote }}
  IGDB_CLIENT_SECRET: {{ .igdb.clientSecret | quote }}
  ROMM_AUTH_SECRET_KEY: {{ .rommAuthSecretKey | quote }}
  STEAMGRIDDB_API_KEY: {{ .steamGridApiKey | quote }}
  SCREENSCRAPER_USER: {{ .screenscraper.user | quote }}
  SCREENSCRAPER_PASSWORD: {{ .screenscraper.password | quote }}
  {{- end }}
