{{ include "baseResources.service" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicas | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend

    spec:
      serviceAccountName: {{ .Release.Name | quote }}
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - {{ include "baseResources.baseContainer" . | nindent 10 }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "{{ .Values.ingress.baseUrl }}"
          envFrom:
            - secretRef:
                name: {{ print .Release.Name "-secret" | quote }}

          {{- with .Values.app.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true

          volumeMounts:
            - name: {{ print .Release.Name "-config" | quote }}
              mountPath: /app/config/
            - name: logs
              mountPath: /app/config/logs

      volumes:
        - name: {{ print .Release.Name "-config" | quote }}
          configMap:
            name: {{ print .Release.Name "-config" | quote }}
        - name: logs
          emptyDir: {}
