apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-server-cert" .Release.Name | quote }}
spec:
  secretName: {{ printf "%s-server-cert" .Release.Name | quote }}
  usages:
    - server auth
  dnsNames:
    - {{ printf "%s.%s" .Release.Name .Values.certificate.domainName | quote }}
    - {{ printf "%s-rw" .Release.Name | quote }}
    - {{ printf "%s-rw.default" .Release.Name | quote }}
    - {{ printf "%s-rw.default.svc" .Release.Name | quote }}
    - {{ printf "%s-r" .Release.Name | quote }}
    - {{ printf "%s-r.default" .Release.Name | quote }}
    - {{ printf "%s-r.default.svc" .Release.Name | quote }}
    - {{ printf "%s-ro" .Release.Name | quote }}
    - {{ printf "%s-ro.default" .Release.Name | quote }}
    - {{ printf "%s-ro.default.svc" .Release.Name | quote }}
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    labels:
      cnpg.io/reload: "true"