apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ print .Release.Name "-cluster" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ .Values.replicaCount }}
  imageName: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: IfNotPresent

  postgresql:
    synchronous:
      method: any
      number: 1
    shared_preload_libraries:
      - "vchord.so"

  certificates:
    serverTLSSecret: {{ print .Release.Name "-server-cert" | quote }}
    serverCASecret: {{ print .Release.Name "-server-cert" | quote }}

  managed:
    roles:
    - name: "{{ .Values.database.immich.username }}"
      ensure: present
      comment: Immich
      login: true
      superuser: false
      passwordSecret:
        name: "{{ .Values.database.immich.username }}-credentials"

    - name: "{{ .Values.database.miniflux.username }}"
      ensure: present
      comment: Miniflux
      login: true
      superuser: false
      passwordSecret:
        name: "{{ .Values.database.miniflux.username }}-credentials"

    - name: "{{ .Values.database.openwebui.username }}"
      ensure: present
      comment: "Open WebUI"
      login: true
      superuser: false
      passwordSecret:
        name: "{{ .Values.database.openwebui.username }}-credentials"
        
    - name: "{{ .Values.database.openwebui.vector.username }}"
      ensure: present
      comment: "Open WebUI Vector"
      login: true
      superuser: false
      passwordSecret:
        name: "{{ .Values.database.openwebui.vector.username }}-credentials"

  storage:
    storageClass: local-storage
    size: 25Gi

  plugins:
  {{- if .Values.backup.enabled }}
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: {{ print .Release.Name "-backup-storage" | quote }}
  {{- end }}