apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ printf "%s-cluster" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ .Values.replicaCount }}
  imageName: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
  imagePullPolicy: IfNotPresent

  postgresql:
    synchronous:
      method: any
      number: 1
    shared_preload_libraries:
      - "vchord.so"

  certificates:
    serverTLSSecret: {{ printf "%s-server-cert" .Release.Name  | quote }}
    serverCASecret: {{ printf "%s-server-cert" .Release.Name  | quote }}

  storage:
    storageClass: local-storage
    size: 25Gi

  plugins:
  {{- if .Values.backup.enabled }}
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: {{ printf "%s-backup-storage" .Release.Name  | quote }}
  {{- end }}