apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: "{{ .Release.Name }}-pooler-rw"
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  cluster:
    name: "{{ .Release.Name }}-cluster"
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "200"
      default_pool_size: "10"