apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ printf "%s-pooler-rw" .Release.Name  | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  cluster:
    name: {{ printf "%s-cluster" .Release.Name  | quote }}
  instances: 2
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "200"
      default_pool_size: "20"
      log_connections: "0"
      log_disconnections: "0"
  serviceTemplate:
    metadata:
      annotations:
        io.cilium/lb-ipam-ips: "{{ .Values.pooler.lb.ip }}"
      labels:
        cilium.lb: "true"
    spec:
      type: LoadBalancer