apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-s3-credentials" .Release.Name  | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  ACCESS_KEY: {{ .Values.backup.accessKey | quote }}
  SECRET_KEY: {{ .Values.backup.secretKey | quote }}