apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Values.mariadb.user }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  name: {{ .Values.mariadb.user }}
  mariaDbRef:
    name: {{ .Values.mariadb.host }}
  passwordSecretKeyRef:
    name: grafana-secret
    key: MYSQL_PASSWORD
  maxUserConnections: 50
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s