{{- if .Values.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: "{{ .Release.Name }}-backup"
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  cluster:
    name: "{{ .Release.Name }}-cluster"
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end }}