{{- if .Values.backup.enabled }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ printf "%s-backup-storage" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  configuration:
    destinationPath: s3://postgres/
    endpointURL: {{ .Values.backup.endpointUrl | quote }}
    endpointCA: 
      name: {{ .Values.certificate.caBundleSecret | quote }}
      key: ca.crt
    s3Credentials:
      accessKeyId:
        name: {{ printf "%s-s3-credentials" .Release.Name | quote }}
        key: ACCESS_KEY
      secretAccessKey:
        name: {{ printf "%s-s3-credentials" .Release.Name | quote }}
        key: SECRET_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
  retentionPolicy: "30d"
{{- end }}