# This requires the grafana-operator - https://github.com/grafana/grafana-operator
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    {{- include "common.labels" . | nindent 4 }}
    dashboards: grafana
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  config:
    global:
      app_mode: "development"
    log:
      mode: "console"
    server:
      root_url: https://{{ .Values.ingress.baseUrl }}
      enable_gzip: "true"
    database:
      type: "{{ .Values.database.type }}"
      url: "mysql://{{ .Values.database.username }}:${MYSQL_PASSWORD}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
      ca_cert_path: /tmp/certs/ca.crt
      server_cert_name: "{{ .Values.database.host }}"
      ssl_mode: "true"
    auth:
      disable_login_form: "true"
    auth.generic_oauth:
      enabled: "true"
      name: OAuth
      icon: signin
      client_id: "${OIDC_CLIENT_ID}"
      # This is bad, fix it...
      client_secret: "{{ .Values.config.oidc.clientSecret }}"
      scopes: openid,email,profile,groups
      empty_scopes: "false"
      auth_url: https://{{ .Values.config.oidc.issuerUrl }}/api/oidc/authorization
      token_url: https://{{ .Values.config.oidc.issuerUrl }}/api/oidc/token
      api_url: https://{{ .Values.config.oidc.issuerUrl }}/api/oidc/userinfo
      login_attribute_path: preferred_username
      groups_attribute_path: groups
      name_attribute_path: name
      use_pkce: "true"
      role_attribute_path: contains(groups[*], 'service-admins') && 'GrafanaAdmin'
      allow_assign_grafana_admin: "true"
      signout_redirect_url: https://{{ .Values.config.oidc.issuerUrl }}/logout
      skip_org_role_sync: "false"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: "{{ .Release.Name }}-secret"
              livenessProbe:
                  httpGet:
                    scheme: HTTP
                    path: /api/health
                    port: {{ .Values.service.port }}
                  initialDelaySeconds: 10
                  periodSeconds: 10
              readinessProbe:
                  httpGet:
                    scheme: HTTP
                    path: /api/health
                    port: {{ .Values.service.port }}
                  initialDelaySeconds: 10
                  periodSeconds: 10
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                seccompProfile:
                  type: RuntimeDefault
              volumeMounts:
                - name: "invis-external-bundle"
                  mountPath: /tmp/certs
                  readOnly: true
          volumes:
            - name: "invis-external-bundle"
              secret:
                secretName: "invis-external-bundle"
