apiVersion: v2
name: AudioMuse
description: A chart for AudioMuse-AI
type: application
version: 0.3.0
appVersion: "3.3.1"

dependencies:
  - name: common-labels
    version: 0.1.0
    repository: "file://../../library/common-labels"

  - name: baseResources
    version: 0.6.0
    repository: "file://../../library/baseResources"

  - name: cnpg
    version: 0.3.0
    repository: "file://../../library/cnpg"