{{- define "redis.fullname" -}}
{{ printf "%s-%s" .Release.Name .Chart.Name | lower | trunc 63 | trimSuffix "-" }}
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: cache
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
