{{- define "redis.service" -}}
{{- $root := .root | default . }}
{{- $vals := .vals | default $root.Values }}
{{- $fullname := include "redis.serviceName" (dict "root" $root) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "common.labels" $root | nindent 4 }}
    app.kubernetes.io/component: cache

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ $root.Release.Name | quote }}
    app.kubernetes.io/component: cache
  ports:
    - protocol: TCP
      port: {{ $vals.port }}
      targetPort: {{ $vals.port }}
{{- end }}