apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ .Values.mariadb.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  name: {{ .Values.mariadb.name }}
  mariaDbRef:
    name: {{ .Values.mariadb.host }}
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s