{{ include "default-svc.service" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicaCount | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      initContainers:
        - name: init-chown
          image: busybox:1.36

          command: ["sh", "-c", "chown -R {{ .Values.app.uid }}:{{ .Values.app.gid }} /data"]

          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: config-pvc
              mountPath: /data

        - name: wait-for-samba
          image: alpine:3.20

          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache samba-client > /dev/null
              echo "Waiting for SMB share "//${SMB_URL}/${SMB_SHARE}"..."
              until smbclient -L "//${SMB_URL}" -U "${SMB_USER}%${SMB_PASS}" -m SMB3 >/dev/null 2>&1; do
                echo "Samba share not ready yet, retrying..."
                sleep 5
              done
              echo "Samba share is available."

          env:
            - name: SMB_URL
              value: "{{ .Values.storage.smb.url }}"
            - name: SMB_SHARE
              value: "{{ .Values.storage.smb.share }}"
            - name: SMB_USER
              value: "{{ .Values.storage.smb.username }}"
            - name: SMB_PASS
              value: "{{ .Values.storage.smb.password }}"

      containers:
        - name: {{ .Release.Name | quote }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - secretRef:
                name: {{ print .Release.Name "-secret" | quote }}
          env:
            - name: ND_CONFIGFILE
              value: /data/navidrome.toml

          {{- with .Values.app.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: config-pvc
              mountPath: /data
            - name: configmap
              mountPath: /data/navidrome.toml
              subPath: navidrome.toml
              readOnly: true
            - name: {{ print .Release.Name "-cache" | quote }}
              mountPath: /data/cache
            - name: {{ print .Release.Name "-music" | quote }}
              mountPath: /music
              readOnly: true

      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: {{ print .Release.Name "-config-pvc" | quote }}
        - name: configmap
          configMap:
            name: {{ print .Release.Name "-configmap" | quote }}
            items:
              - key: navidrome.toml
                path: navidrome.toml
        - name: {{ print .Release.Name "-music" | quote }}
          persistentVolumeClaim:
            claimName: {{ print .Release.Name "-music" | quote }}
        - name: {{ print .Release.Name "-cache" | quote }}
          emptyDir:
            medium: Memory
