apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-music" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  volumeName: {{ print .Release.Name "-music" | quote }}
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-config-pvc" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
{{- with .Values.storage.config }}
  volumeName: {{ .volumeName | quote }}
{{- end }}