{{- $root := .root | default . }}
{{- $vals := .vals | default $root.Values.app }}
{{- $serviceName := include "baseResources.serviceName" (dict "root" $root "vals" $vals) }}

apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ printf "%s-tls-policy" .Release.Name }}
spec:

  targetRefs:
    - group: ""
      kind: Service
      name: {{ $serviceName }}
      sectionName: https

  validation:
    hostname: {{ printf "%s.%s.svc.cluster.local" $serviceName $root.Release.Namespace }}
    caCertificateRefs:
      - name: {{ printf "%s-server-cert" .Release.Name }}
        group: ""
        kind: Secret