{{- $root := .root | default . }}
{{- $vals := .vals | default $root.Values.app }}
{{- $serviceName := include "baseResources.serviceName" (dict "root" $root "vals" $vals) }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-server-cert" .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  secretName: {{ printf "%s-server-cert" .Release.Name }}
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  commonName: {{ printf "%s.%s.svc.cluster.local" $serviceName $root.Release.Namespace }}
  dnsNames:
    - {{ printf "%s.%s.svc.cluster.local" $serviceName $root.Release.Namespace }}
    - {{ printf "%s.%s.svc.cluster" $serviceName $root.Release.Namespace }}
    - {{ printf "%s.%s.svc" $serviceName $root.Release.Namespace }}
    - {{ printf "%s.%s" $serviceName $root.Release.Namespace }}
    - {{ printf "%s" $serviceName}}
    - localhost
