apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  RUN_MIGRATIONS: "1"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  BASE_URL: {{ printf "https://%s" .Values.app.route.baseUrl | quote }}
  CERT_FILE: "/etc/cert/tls.crt"
  KEY_FILE: "/etc/cert/tls.key"
  DISABLE_LOCAL_AUTH: "true"
  HTTPS: "true"
  PORT: "443"
  POLLING_FREQUENCY: "15"
  CLEANUP_ARCHIVE_READ_DAYS: "30"
  CLEANUP_ARCHIVE_UNREAD_DAYS: "60"