{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}

    spec:
      automountServiceAccountToken: false
      initContainers:
        - {{ include "baseResources.waitForPostgres" (dict "root" $ "vals" $.Values) | nindent 10 }}

      containers:
        - {{ include "baseResources.baseContainer" (dict "root" $ "vals" .) | nindent 10 }}

          ports:
            {{- range .service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}

          {{- with .resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          securityContext:
            runAsUser: {{ .uid }}
            runAsGroup: {{ .gid }}
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: certs
              mountPath: "/etc/cert"
              readOnly: true

      volumes:
        - name: certs
          secret:
            secretName: {{ printf "%s-server-cert" $.Release.Name }}
{{- end }}