{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.mainDb }}
{{ include "cnpg.database" (dict "root" $ "vals" . ) }}
---
{{ include "cnpg.role" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}

    spec:
      automountServiceAccountToken: false
      initContainers:
        {{- include "baseResources.waitForPostgres" $.Values.mainDb | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}

          volumeMounts:
            - name: certs
              mountPath: "/etc/cert"
              readOnly: true

      volumes:
        - name: certs
          secret:
            secretName: {{ printf "%s-server-cert" $.Release.Name }}
{{- end }}