apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
type: Opaque
stringData:
  OAUTH2_PROVIDER: "oidc"
  OAUTH2_USER_CREATION: "true"
  {{- with .Values.env.oidc }}
  OAUTH2_CLIENT_ID: {{ .clientID | quote }}
  OAUTH2_CLIENT_SECRET: {{ required "env.oidc.clientSecret is required" .clientSecret | quote }}
  OAUTH2_OIDC_DISCOVERY_ENDPOINT: {{ .url | quote }}
  OAUTH2_OIDC_PROVIDER_NAME: {{ .name | quote }}
  OAUTH2_REDIRECT_URL: {{ .redirectUrl | quote }}
  {{- end }}

  {{- with .Values.mainDb }}
  DATABASE_URL: {{ printf "host=%s port=%s dbname=%s user=%s password=%s" .host .port .name .owner .password | quote }}
  {{- end }}