apiVersion: v2
name: Technitium
description: A Helm chart for Technitium
type: application
version: 0.2.0
appVersion: "14.3.0"

dependencies:
  - name: common-labels
    version: 0.1.0
    repository: "file://../../library/common-labels"

  - name: baseResources
    version: 0.1.0
    repository: "file://../../library/baseResources"
