apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-longhorn-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-delete-single
