apiVersion: v2
name: VictoriaMetrics
description: VictoriaMetrics cluster and some scrape configs
type: application
version: 0.1.0
appVersion: v1.131.0-cluster

dependencies:
  - name: common-labels
    version: 0.1.0
    repository: "file://../../library/common-labels"
