app:
  # -- App name
  name: grafana
  image:
    repository: grafana/grafana
    tag: 12.1.0

database:
  # -- Kind of database
  type: mysql
  # -- FQDN to database
  host:
  # -- Database deployment name
  instanceName:
  # -- Database namespace
  namespace:
  # -- Database port
  port: 3306
  # -- Database name
  name:
  # -- Database username
  username:
  # -- Database password
  password:

service:
  # App port
  port: 3000

ingress:
  # FQDN to the application
  baseUrl:

smtp:
  enabled:
  host:
  user:
  password:
  fromAddress:

config:
  oidc:
    # -- OIDC endpoint URL
    url:
    # -- App client secret
    clientSecret:

  datasource:
    tlsSkipVerify: true
    vmkube:
      pluginName: victoriametrics-metrics-datasource
      version: 0.19.5
      url:
    vm:
      pluginName: victoriametrics-metrics-datasource
      version: 0.19.5
      url:
    vl:
      pluginName: victoriametrics-logs-datasource
      version: 0.21.1
      url:

  contactpoint:
    mailAddress:
