apiVersion: v1
kind: Secret
metadata:
  name: {{ print .Release.Name "-secret" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
type: Opaque
stringData:
    DNS_SERVER_ADMIN_PASSWORD: "{{ .Values.config.dnsServerAdminPassword }}"