{{ include "baseResources.service" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Release.Name "-lb" | quote }}
  labels:
    app.kubernetes.io/name: "{{ .Values.app.name | default .Chart.Name }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    cilium.lb: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.40.40.210
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53