# This requires traefik crds - https://doc.traefik.io/traefik/getting-started/quick-start-with-kubernetes/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-route"
  labels:
    app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.baseUrl }}`)
      services:
        - kind: Service
          name: "{{ .Release.Name }}-svc"
          port: {{ .Values.service.port }}
      middlewares:
        - name: "authelia-forward-auth"
          namespace: traefik
