apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-redis"
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.redis.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: "{{ .Release.Name }}-redis"
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          args: 
            - "--in-memory"
          ports:
            - containerPort: {{ .Values.redis.port }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: REDIS_PASSWORD
          resources:
          {{- toYaml ( .Values.redis.resources | default dict ) | nindent 12 }}
          livenessProbe:
          {{- toYaml ( .Values.redis.livenessProbe | default dict ) | nindent 12 }}
          readinessProbe:
          {{- toYaml ( .Values.redis.readinessProbe | default dict ) | nindent 12 }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
