apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-server-cert
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-server-cert
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  commonName: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
    - "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
    - "{{ .Release.Name }}.{{ .Release.Namespace }}.svc"
    - "{{ .Release.Name }}.{{ .Release.Namespace }}"
    - "{{ .Release.Name }}"
    - "localhost"
