apiVersion: v2
name: Technitium
description: A Helm chart for Technitium
type: application
version: 0.2.0
appVersion: "13.6.0"

dependencies:
  - name: common-labels
    version: 0.1.0
    repository: "file://../library/common-labels"

  - name: default-svc
    version: 0.1.0
    repository: "file://../library/default-svc"
