app:
  # -- App name
  name: technitium
  # -- Number of pods
  replicaCount: 1

  image:
    # -- App image
    repository: technitium/dns-server
    # -- App version
    tag: 14.3.0
    # -- Image pull policy
    pullPolicy: Always

  # -- Runtime user
  uid: 1001
  # -- Runtime group
  gid: 1001

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      memory: "512Mi"

  livenessProbe:
    exec:
      command:
        [
          "sh",
          "-c",
          "dig +short +retry=0 +norecurse @127.0.0.1 localhost | grep 127.0.0.1",
        ]
    initialDelaySeconds: 5
    periodSeconds: 20
  readinessProbe:
    exec:
      command:
        [
          "sh",
          "-c",
          "dig +short +retry=0 +norecurse @127.0.0.1 localhost | grep 127.0.0.1",
        ]
    initialDelaySeconds: 5
    periodSeconds: 10

service:
  # -- App port
  port: 5380

ingress:
  # -- FQDN for application
  baseUrl:

config:
  # -- Root domain
  dnsServerDomain:
  # -- Admin password
  dnsServerAdminPassword:
