{{- define "cnpg.credentials" -}}
{{- $root := .root | default . }}
{{- $vals := .vals | default $root.Values }}
{{- $fullname := printf "%s-credentials" $vals.owner }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname | quote }}
  namespace: {{ $vals.namespace | default $root.Release.Namespace }}
  labels:
    {{- include "common.labels" $root | nindent 4 }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: {{ required "$vals.owner is required" $vals.owner | quote }}
    password: {{ required "$vals.password is required" $vals.password | quote }}
{{- end }}