app:
  # -- App name
  name: navidrome
  replicaCount: 1

  image:
    repository: ghcr.io/navidrome/navidrome
    tag: 0.58.0

  # -- Runtime user
  uid: 1001
  # -- Runtime group
  gid: 1001

  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      memory: "512Mi"

service:
  # -- App port
  port: 4533

ingress:
  # -- FQDN for the application
  baseUrl:

middleware:
  whitelist:
    ip:

storage:
  smb:
    url:

  existingPvcName:

config:
  reverseProxyWhitelist:
  smbUser:
  smbPassword:
