apiVersion: v2
name: Homepage
description: A Helm chart for Homepage
type: application
version: 0.2.0
appVersion: "v1.9.0"

dependencies:
  - name: common-labels
    version: 0.1.0
    repository: "file://../../library/common-labels"

  - name: baseResources
    version: 0.1.0
    repository: "file://../../library/baseResources"
