apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicas | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: "{{ .Release.Name }}"
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: init-chown
          image: busybox:1.36
          command: ["sh", "-c", "chown -R {{ .Values.app.uid }}:{{ .Values.app.gid }} /data"]
          volumeMounts:
            - name: "{{ .Release.Name }}-persistence"
              mountPath: /data
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "{{ .Values.ingress.baseUrl }}"
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secret"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
          {{- toYaml ( .Values.app.resources | default dict ) | nindent 12 }}
          livenessProbe:
          {{- toYaml ( .Values.app.livenessProbe | default dict ) | nindent 12 }}
          readinessProbe:
          {{- toYaml ( .Values.app.readinessProbe | default dict ) | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          volumeMounts:
            - name: "{{ .Release.Name }}-config"
              mountPath: /app/config/
            - name: logs
              mountPath: /app/config/logs
            - name: "{{ .Release.Name }}-persistence"
              mountPath: /app/public/images
      volumes:
        - name: "{{ .Release.Name }}-persistence"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-pvc"
        - name: "{{ .Release.Name }}-config"
          configMap:
            name: "{{ .Release.Name }}-config"
        - name: logs
          emptyDir: {}
