apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-route"
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.baseUrl }}`)
      services:
        - kind: Service
          name: "{{ .Release.Name }}-svc"
          port: {{ .Values.service.port }}
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
      middlewares:
        - name: "authelia-forward-auth"
          namespace: traefik
