apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: "home-lb-pool1"
spec:
  blocks:
  - start: "10.40.40.201"
    stop: "10.40.40.254"
  serviceSelector:
    matchLabels:
      cilium.lb: "true"