apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ .Release.Name }}-db
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  name: "{{ .Values.database.name }}"
  mariaDbRef:
    name: "{{ .Values.database.instanceName }}"
    namespace: "{{ .Values.database.namespace }}"
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s