{{- with .Values.bind }}
{{- $fullname := include "baseResources.fullname" (dict "root" $ "vals" .) }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" $fullname | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  named.conf: |
    logging {
        channel default_log {
            stderr;
            severity warning;
            print-time yes;
            print-category yes;
            print-severity yes;
        };

        channel null {
            null;
        };

        category rpz {
            null;
        };

        category dnssec {
            null;
        };

        category default {
            default_log;
        };
    };

    acl this_server {
    {{- range $.Values.acls.this_server }}
      {{ . }};
    {{- end }}
    };

    acl home_net {
    {{- range $.Values.acls.home_net }}
      {{ . }};
    {{- end }}
    };

    acl vpn {
    {{- range $.Values.acls.vpn }}
      {{ . }};
    {{- end }}
    };

    acl k8s_pods {
    {{- range $.Values.acls.k8s_pods }}
      {{ . }};
    {{- end }}
    };

    trust-anchors {
      "invis.space." initial-ds 14785 8 2 "00E36912D43A8A42A5BC865AC758F809C7DCED4CB350D72E7737CD18D19F7FA8";
      "10.10.10.in-addr.arpa." initial-ds 50300 8 2 "9477A53D4C629045C7E4D5B5DDF6BF396702F2D9F4B4E34B08F701805FF51154";
      "20.20.10.in-addr.arpa." initial-ds 3500 8 2 "DD31FA2DF4D499202E5A0D891AA8BA4BBEF8C0BA538147370C2559F7C0107AAB";
      "40.40.10.in-addr.arpa." initial-ds 61727 8 2 "D7B1FDE00C879153D7E2195D5E3481688D0FF7A897B7A7317D8E32BBDFCEF5D4";
      "255.255.10.in-addr.arpa." initial-ds 23975 8 2 "80E5FD7BF112551DC04DAF50DD2CB3A32823FC3D8CABF65F06070B002A1393BA";
    };

    options {
      directory "/var/cache/bind";

      listen-on port 53 {
          any;
      };

      listen-on-v6 {
          none;
      };

      forwarders {
        1.1.1.1;
        8.8.8.8;
      };

      response-policy {
          zone "local-block";
          zone "hagezi";
      };

      forward first;

      recursion yes;
      rate-limit {
          responses-per-second 15;
      };

      allow-query { home_net; vpn; k8s_pods; };
      allow-query-cache { localhost; home_net; vpn; k8s_pods; };
      allow-recursion { home_net; vpn; k8s_pods; };
      allow-transfer { none; };
      deny-answer-addresses { this_server; };

      dnssec-validation auto;
      empty-zones-enable yes;
      minimal-responses yes;

      version "not currently available";
    };

    zone "local-block" {
        type master;
        file "/etc/bind/local-block.zone";
    };

    zone "hagezi" {
        type master;
        file "/rpz/hagezi.rpz";
    };

    {{- range $.Values.zones.zones }}
    zone "{{ . }}" {
      type forward;
      forward only;
      forwarders {
        {{- range $.Values.zones.forwarders }}
        {{ . }};
        {{- end }}
      };
    };
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-local-block" $fullname }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  local-block.zone: |
    $TTL 60

    @ IN SOA localhost. root.localhost. (
        2026060301 ; serial
        3H         ; refresh
        1H         ; retry
        1W         ; expiry
        1H         ; minimum
    )

    @ IN NS localhost.

    snu.lge.com CNAME .
    su.lge.com  CNAME .

{{- end }}