appName: observability-metrics
vmagent:
  replicaCount: 1

  image:
    repo: victoriametrics/vmagent
    tag: v1.96.0

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi

ksm:
  replicaCount: 1

  image:
    repo: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: v2.16.0

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

config:
  remoteWriteUrl:

  scrapeInterval: 10s
