{{- with .Values.backup }}
{{- $mariadbName := include "mariadb.fullname" $ -}}

apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: {{ printf "%s-backup" $mariadbName }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  mariaDbRef:
    name: {{ $mariadbName }}
  maxRetention: 720h # 30 days
  compression: gzip
  storage:
    s3:
      bucket: mariadb
      prefix: mariadb
      endpoint: {{ .endpoint | quote }}
      region:  us-east-1
      accessKeyIdSecretKeyRef:
        name: {{ printf "%s-s3-credentials" $mariadbName }}
        key: ACCESS_KEY
      secretAccessKeySecretKeyRef:
        name: {{ printf "%s-s3-credentials" $mariadbName }}
        key: SECRET_KEY
      tls:
        enabled: true
        caSecretKeyRef:
          name: invis-external-bundle
          key: ca.crt
  schedule:
    cron: {{ .schedule | quote }}
    suspend: false
{{- end }}
