{{- $mariadbName := include "mariadb.fullname" $ -}}

{{ with .Values.maxScale }}
{{ include "baseResources.httproute" (dict "root" $ "vals" $.Values.maxScale) }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: {{ include "maxscale.fullname" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  mariaDbRef:
    name: {{ $mariadbName }}

  services:
    - name: rw-router
      router: readwritesplit
      params:
        transaction_replay: "true"
        transaction_replay_attempts: "10"
        transaction_replay_timeout: "5s"
        max_slave_connections: "255"
        max_replication_lag: "3s"
        master_accept_reads: "true"
      listener:
        port: 3306
        protocol: MariaDBProtocol
        params:
          connection_metadata: "tx_isolation=auto"

  admin:
    port: 8989
    guiEnabled: true

  auth:
    generate: true
    adminUsername: {{ .adminUsername }}
    adminPasswordSecretKeyRef:
      name: {{ printf "%s-maxscale-admin" $mariadbName }}
      key: ADMIN_PASSWORD

  tls:
    enabled: true
    serverCASecretRef:
      name: {{ printf "%s-ca-bundle" $mariadbName }}
    serverCertSecretRef:
      name: {{ printf "%s-client-cert" $mariadbName }}
    adminCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
    listenerCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

  kubernetesService:
    type: {{ .service.type }}
    metadata:
      annotations:
        io.cilium/lb-ipam-ips: {{ .service.loadBalancerIP | quote }}
      labels:
        cilium.lb: "true"

  metrics:
    enabled: true
    exporter:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
      podSecurityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

    serviceMonitor:
      jobLabel: maxscale-metrics
{{- end }}
