{{- if .Values.maxScale.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: {{ .Release.Name }}-maxscale
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  mariaDbRef:
    name: {{ .Release.Name }}

  services:
    - name: rw-router
      router: readwritesplit
      params:
        transaction_replay: "true"
        transaction_replay_attempts: "10"
        transaction_replay_timeout: "5s"
        max_slave_connections: "255"
        max_replication_lag: "3s"
        master_accept_reads: "true"
      listener:
        port: 3306
        protocol: MariaDBProtocol
        params:
          connection_metadata: "tx_isolation=auto"
    - name: rconn-master-router
      router: readconnroute
      params:
        router_options: "master"
        max_replication_lag: "3s"
        master_accept_reads: "true"
      listener:
        port: 3307
    - name: rconn-slave-router
      router: readconnroute
      params:
        router_options: "slave"
        max_replication_lag: "3s"
      listener:
        port: 3308

  admin:
    port: 8989
    guiEnabled: true

  auth:
    generate: true

  tls:
    enabled: true
    serverCASecretRef:
      name: {{ .Release.Name }}-ca-bundle
    serverCertSecretRef:
      name: {{ .Release.Name }}-client-cert
    adminCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
    listenerCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer

  securityContext:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]

  kubernetesService:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: "{{ .Values.maxScale.metalLB.ip }}"
{{- end }}