{{- if .Values.maxScale.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: {{ .Release.Name }}-maxscale
spec:
  mariaDbRef:
    name: {{ .Release.Name }}

  auth:
    generate: true

  tls:
    enabled: true
    serverCASecretRef:
      name: {{ .Release.Name }}-ca-bundle
    serverCertSecretRef:
      name: {{ .Release.Name }}-client-cert
    adminCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
    listenerCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

  kubernetesService:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: "{{ .Values.maxScale.metalLB.ip }}"
{{- end }}