{{- $mariadbName := include "mariadb.fullname" $ -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" $mariadbName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
    ROOT_PASSWORD: {{ .Values.app.rootPassword | quote }}
---
{{- if .Values.maxScale }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-maxscale-admin" $mariadbName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
    ADMIN_PASSWORD: {{ .Values.maxScale.adminPassword | quote }}
{{- end }}
---
{{- if .Values.backup }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-s3-credentials" $mariadbName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_KEY: {{ required ".backup.accessKey is required" .Values.backup.accessKey | quote }}
  SECRET_KEY: {{ required ".backup.secretKey is required" .Values.backup.secretKey | quote }}
{{- end }}