apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "technitium" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.network.webPort }}
      targetPort: {{ .Values.network.webPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "technitium" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: 10.40.40.210
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
---
# This requires traefik crds - https://doc.traefik.io/traefik/getting-started/quick-start-with-kubernetes/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-route
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "technitium" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Technitium
    gethomepage.dev/description: DNS Server
    gethomepage.dev/icon: technitium.png
    gethomepage.dev/href: "https://{{ .Values.network.baseUrl }}"
    gethomepage.dev/pod-selector: "app.kubernetes.io/component=frontend"
    gethomepage.dev/group: Frontend
    gethomepage.dev/weight: "5"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.network.baseUrl }}`)
      services:
        - kind: Service
          name: {{ .Release.Name }}-svc
          port: {{ .Values.network.webPort }}
