apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data: # Place config files into files directory
{{- range $path, $bytes := .Files.Glob "files/*.yml" }}
  {{ base $path }}: |-
{{ $bytes | toString | indent 4 }}
{{- end }}