{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        fsGroup: {{ printf "%d" (int64 .gid) }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - secretRef:
                name: {{ $.Release.Name }}-secret

          volumeMounts:
            - name: assets
              mountPath: /app/assets
          {{- range $path, $_ := $.Files.Glob "files/*.yml" }}
            - name: config
              mountPath: /app/config/{{ base $path }}
              subPath: {{ base $path }}
          {{- end }}

      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: {{ $.Release.Name }}-assets
        - name: config
          configMap:
            name: {{ $.Release.Name }}-config
{{- end }}