{{ include "baseResources.service" (dict "root" $ "vals" .Values.app) }}
---
{{ include "baseResources.httproute" (dict "root" $ "vals" .Values.app) }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component | quote }}
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      app.kubernetes.io/component: {{ .component | quote }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component | quote }}

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        fsGroup: {{ printf "%d" (int64 .gid) }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name | quote }}

          volumeMounts:
            - name: assets
              mountPath: /app/assets
          {{- range $path, $_ := $.Files.Glob "files/*.yml" }}
            - name: config
              mountPath: {{ printf "/app/config/%s" (base $path) | quote }}
              subPath: {{ base $path }}
          {{- end }}

      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: {{ printf "%s-assets" $.Release.Name | quote }}
        - name: config
          configMap:
            name: {{ printf "%s-config" $.Release.Name | quote }}
{{- end }}