apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-assets" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi