{{- with .Values }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" $.Release.Name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  TZ: "Europe/Stockholm"
  IMMICH_VERSION: "v3"
  DISABLE_REVERSE_GEOCODING: "false"
  REVERSE_GEOCODING_PRECISION: "2"
  PUBLIC_LOGIN_PAGE_MESSAGE: ""
  IMMICH_HELMET_FILE: "true"
  IMMICH_LOG_FORMAT: "json"
  IMMICH_MACHINE_LEARNING_URL: {{ .config.machineLearning.url | quote }}

  # Redis
  REDIS_HOSTNAME: {{ include "redis.serviceFQDN" (dict "root" $) | quote }}
  REDIS_PORT: {{ .redis.port | quote }}
  REDIS_USERNAME: {{ .redis.user | quote }}

  # Database
  DB_DATABASE_NAME: {{ .mainDb.name | quote }}
  DB_HOSTNAME: {{ .mainDb.host | quote }}
  DB_USERNAME: {{ .mainDb.owner | quote }}
{{- end }}