{{- $redis := dict "Chart" (dict "Name" "redis") "Release" .Release "Values" .Values.redis -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print .Release.Name "-env" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  TZ: "Europe/Stockholm"
  DB_DATABASE_NAME: {{ .Values.mainDb.name | quote }}
  DB_HOSTNAME: {{ .Values.mainDb.host | quote }}
  DB_USERNAME: {{ .Values.mainDb.owner | quote }}
  IMMICH_MACHINE_LEARNING_URL: "{{ .Values.config.machineLearning.url }}"
  REDIS_HOSTNAME: {{ include "redis.fullname" $redis | quote }}
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_USERNAME: "{{ .Values.redis.user }}"
  DISABLE_REVERSE_GEOCODING: "false"
  REVERSE_GEOCODING_PRECISION: "2"
  PUBLIC_LOGIN_PAGE_MESSAGE: ""
