{{ include "baseResources.service" . }}
---
{{ include "baseResources.ingress" . }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ print .Release.Name "-server" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      automountServiceAccountToken: false
      initContainers:
        - {{ include "baseResources.waitForPostgres" . | nindent 10 }}

      containers:
        - {{ include "baseResources.baseContainer" . | nindent 10 }}

          envFrom:
            - configMapRef:
                name: {{ print .Release.Name "-env" | quote }}
                optional: false
            - secretRef:
                name: {{ print .Release.Name "-secret" | quote }}
                optional: false

          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          {{- with .Values.app.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: library
              mountPath: /data

      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: {{ print .Release.Name "-upload-pvc" | quote }}
