{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-server" $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}
  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}
    spec:
      automountServiceAccountToken: false
      initContainers:
        {{- include "baseResources.waitForPostgres" $.Values.mainDb | nindent 8 }}

        {{- include "baseResources.waitForSamba" $.Values.storage.smb | nindent 8 }}


      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
                optional: false
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}
                optional: false

          volumeMounts:
            - name: library
              mountPath: /data

      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: {{ printf "%s-upload-pvc" $.Release.Name }}
{{- end }}