kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-upload-pvc" .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: {{ printf "%s-upload-pv" .Release.Name }}
  storageClassName: ""
