app:
  # -- App name
  name: bookstack
  # -- Number of pods
  replicaCount: 1

  image:
    # -- App image
    repository: solidnerd/bookstack
    # -- Image version
    tag: 25.2
    # -- Image pull policy
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      memory: "256Mi"

  healthCheck:
    enabled: true
    scheme: HTTP
    path: /status
    initialDelay: 10
    periodSeconds: 10

storage:
  size:

database:
  enabled: true

  # -- FQDN to database
  host:
  # -- Database deployment name
  instanceName:
  # -- Database namespace
  namespace:
  # -- Database port
  port: 3306
  # -- Database name
  name:
  # -- Database user
  username:
  # -- Database password
  password:

service:
  # -- App port
  port: 8080

ingress:
  enabled: true
  # -- FQDN to application
  baseUrl:

config:
  appKey:

  oidc:
    # -- OIDC name
    name:
    # -- OIDC endpoint URL
    url:
    # -- App client ID
    clientId:
    # -- App client secret
    clientSecret:
    # -- Logout URL
    endSessionEndpoint:
    displayNameClaims:
