apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  navidrome.toml: |
    LogLevel = 'info'
    EnableInsightsCollector = 'false'
    BaseUrl = 'https://{{ .Values.ingress.baseUrl }}'
    ReverseProxyWhitelist = '{{ .Values.config.reverseProxyWhitelist }}'
    ReverseProxyUserHeader = 'Remote-User'

    LastFM.Enabled = 'true'
    Deezer.Enabled = 'true'
    ListenBrainz.Enabled = 'false'
    Agents = 'deezer,lastfm'
    LastFM.Language = 'en'

    EnableCoverAnimation = 'true'
    EnableSharing = 'false'
    DefaultTheme = 'nord'
    AutoImportPlaylists = 'true'
    SessionTimeout = '48h'
    EnableStarRating = 'false'
    Scanner.Enabled = 'true'
    Scanner.WatcherWait = '5s'
    Scanner.ScanOnStartup = 'true'
