# This volume requires smb csi drivers - https://github.com/kubernetes-csi/csi-driver-smb
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-music
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "navidrome" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - file_mode=0664
    - dir_mode=02775
    - uid={{ .Values.storage.smbUid }} # svc-navidrome
    - gid={{ .Values.storage.smbGid }} # storage-access
    - noperm
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: {{ .Release.Name }}-music-volume
    volumeAttributes:
      source: {{ .Values.storage.smbShare }}
    nodeStageSecretRef:
      name: {{ .Release.Name }}-smb-credentials
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-music
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "navidrome" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  volumeName: {{ .Release.Name }}-music
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config-pvc
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "navidrome" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- if .Values.storage.existingPvcName }}
  volumeName: {{ .Values.storage.existingPvcName }}
{{- end }}