apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "navidrome" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicas | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName | default "navidrome" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      initContainers:
        - name: init-chown
          image: busybox:1.36
          command: ["sh", "-c", "chown -R {{ .Values.app.uid }}:{{ .Values.app.gid }} /data"]
          volumeMounts:
            - name: config-pvc
              mountPath: /data
    spec:
      initContainers:
        - name: init-chown
          image: busybox:1.36
          command: ["sh", "-c", "chown -R {{ .Values.app.uid }}:{{ .Values.app.gid }} /data"]
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: {{ .Release.Name }}-resources
              mountPath: /data
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.app.image.repo }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.network.port }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            - name: ND_CONFIGFILE
              value: /data/navidrome.toml
          resources:
          {{- toYaml .Values.app.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: {{ .Values.network.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: {{ .Values.network.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config-pvc
              mountPath: /data
            - name: configmap
              mountPath: /data/navidrome.toml
              subPath: navidrome.toml
            - mountPath: /data/cache
              name: {{ .Release.Name }}-cache
            - name: {{ .Release.Name }}-music
              mountPath: /music
              readOnly: true
      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
        - name: configmap
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: navidrome.toml
                path: navidrome.toml
        - name: {{ .Release.Name }}-secret
          secret:
            secretName: {{ .Release.Name }}-secret
        - name: {{ .Release.Name }}-music
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-music
        - name: {{ .Release.Name }}-cache
          emptyDir:
            medium: Memory
