{{- if .Values.mariadb.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: db-{{ .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  storage:
    size: {{ .Values.mariadb.storage.size }}
  replicas: {{ .Values.mariadb.replicas | default 1 }}
  resources:
  {{- toYaml .Values.mariadb.resources | nindent 4 }}
  {{- if .Values.mariadb.healthCheck.enabled }}
  livenessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 5
  startupProbe:
    failureThreshold: 10
    periodSeconds: 5
    timeoutSeconds: 5
  {{- end }}
  service:
    type: ClusterIP
    sessionAffinity: None
  {{- if .Values.mariadb.tls.enabled }}
  tls:
    enabled: true
    required: true
    serverCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
  {{- end }}
{{- end }}