apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-config" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
