apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-lb"
  labels:
    app.kubernetes.io/name: "{{ .Values.app.name | default .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.40.40.210
  selector:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53