appName: omnitools
app:
  replicaCount: 1

  image:
    repository: iib0011/omni-tools
    tag: 0.6.0

  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      memory: "1Gi"

service:
  port: 80

ingress:
  baseUrl:
