{{- with .Values.blackbox }}
{{- $fullname := include "baseResources.fullname" (dict "root" $ "vals" .) }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-config
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  blackbox.yml: |
    modules:
      default:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: []
          valid_status_codes: []
          method: GET
          follow_redirects: true
          tls_config:
            insecure_skip_verify: true
            # ca_file: "/data/certs/ca.crt"
    
      default_basic_auth:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: []
          valid_status_codes: []
          method: GET
          follow_redirects: true
          tls_config:
            insecure_skip_verify: true
            # ca_file: "/data/certs/ca.crt"
          basic_auth:
            username: {{ .auth.user }}
            password: {{ .auth.password }}
{{- end }}