{{- $fullname := include "app.fullname" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-blackbox
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"

{{- with .Values.blackbox }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}

    spec:
      securityContext:
        fsGroup: {{ .gid }}

      containers:
        - {{ include "baseResources.baseContainer" . | nindent 10 }}

          ports:
            - containerPort: {{ .service.port }}

          {{- if .resources }}
          resources:
          {{- toYaml .resources | nindent 12 }}
          {{- end }}

          {{- if .livenessProbe }}
          livenessProbe:
          {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}

          {{- if .readinessProbe }}
          readinessProbe:
          {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}

          securityContext:
            runAsUser: {{ .uid }}
            runAsGroup: {{ .gid }}
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
{{- end }}