{{- with .Values.vmagent }}
{{- $fullname := include "baseResources.fullname" (dict "root" $ "vals" .) }}

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  selectAllByDefault: true

  remoteWrite:
    - url: "{{ .remoteWriteUrl }}"
{{- end }}