{{- $fullname := include "app.fullname" . }}

{{- with .Values.victoriametrics }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  replicationFactor: 2
  clusterVersion: "{{ .image.tag }}"
  retentionPeriod: "1" # Month

  requestsLoadBalancer:
    enabled: true
    spec:
      replicaCount: 2

  vmstorage:
    podMetadata:
      labels:
        app.kubernetes.io/component: storage
    replicaCount: 3
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "local-storage"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/component"
                operator: In
                values: ["storage"]
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 2048Mi

  vmselect:
    podMetadata:
      labels:
        app.kubernetes.io/component: frontend
    replicaCount: 2
    cacheMountPath: "/select-cache"
    storage:
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/component"
                operator: In
                values: ["frontend"]
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        memory: 1500Mi

  vminsert:
    podMetadata:
      labels:
        app.kubernetes.io/component: ingestion
    replicaCount: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/component"
                operator: In
                values: ["ingestion"]
          topologyKey: "kubernetes.io/hostname"
    # VMInsertInternal port
    insertPorts:
      graphitePort: "2003"

    # VMInsert for Graphite
    serviceSpec:
      metadata:
        name: {{ $fullname }}-graphite-svc
        annotations:
          io.cilium/lb-ipam-ips: "{{ .graphite.metallb.ip }}"
        labels:
          {{- include "common.labels" $ | nindent 10 }}
          cilium.lb: "true"
      spec:
        type: LoadBalancer
        ports:
          - name: graphite-tcp
            port: 2003
            targetPort: 2003
            protocol: TCP
          - name: graphite-udp
            port: 2003
            targetPort: 2003
            protocol: UDP

    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        memory: 500Mi
{{- end }}