{{- range .Values.vmprobe }}
{{- $fullname := include "baseResources.fullname" (dict "root" $ "vals" .) }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
    name: {{ $fullname }}
spec:
    jobName: {{ $.Values.blackbox.name }}
    vmProberSpec:
        url: "{{ include "baseResources.fullname" (dict "root" $ "vals" $.Values.blackbox) }}-svc.{{ $.Release.Namespace }}.svc:{{ (index $.Values.blackbox.service.ports 0).port }}"
    module: {{ .module }}
    targets:
        static:
            targets:
{{- range .targets }}
                - {{ . | quote }}
{{- end }}
    interval: 10s

    metricRelabelConfigs:
        - action: labeldrop
          regex: "^prometheus$"
{{- end }}