apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_ID: "{{ .Values.config.oidc.clientId }}"
  OIDC_CLIENT_SECRET: "{{ .Values.config.oidc.clientSecret }}"
  OIDC_CLIENT_CRYPTO_KEY: "{{ .Values.config.oidc.cryptoKey }}"
  SALT: "{{ .Values.config.salt }}"
  DB_PASSWD: "{{ .Values.database.password }}"
