{{- $root := . -}}
{{- $config := $root.Values.config -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" $root.Release.Name | quote }}
  labels:
    {{- include "common.labels" $root | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  # General
  X_AUTHELIA_CONFIG_FILTERS: "template"

  # Secret file paths
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: {{ printf "%s/LDAP_PASSWORD" $config.secretsDir | quote }}
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: {{ printf "%s/OIDC_HMAC_SECRET" $config.secretsDir | quote }}
  AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: {{ printf "%s/JWT_SECRET" $config.secretsDir | quote }}
  AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: {{ printf "%s/LDAP_PASSWORD" $config.secretsDir | quote }}
  AUTHELIA_SESSION_REDIS_PASSWORD_FILE: {{ printf "%s/REDIS_PASSWORD" $config.secretsDir | quote }}
  AUTHELIA_SESSION_SECRET_FILE: {{ printf "%s/SESSION_SECRET" $config.secretsDir | quote }}
  AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: {{ printf "%s/STORAGE_ENCRYPTION_KEY" $config.secretsDir | quote }}
  AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE: {{ printf "%s/MYSQL_PASSWORD" $config.secretsDir | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data: # Place config files into files directory
{{- range $path, $bytes := .Files.Glob "files/*.yml" }}
  {{ base $path }}: |-
{{ tpl ($bytes | toString) $ | indent 4 }}
{{- end }}