{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .name | default $.Chart.Name }}"
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false

      initContainers:
        - {{ include "baseResources.waitForMariadb" (dict "root" $ "vals" $.Values) | nindent 10 }}

      containers:
        - {{ include "baseResources.baseContainer" (dict "root" $ "vals" . ) | indent 10 }}

          command:
            - authelia
          args:
            - "--config=/config/configuration.yml"
            - "--config=/config/configuration.clients.yml"

          ports:
            {{- range .service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
            
          securityContext:
            runAsUser: {{ .uid }}
            runAsGroup: {{ .gid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}

          {{- with .resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: config
              mountPath: /config
            - name: certs
              mountPath: /tmp/certs
              readOnly: true
            - name: secret
              mountPath: "{{ $.Values.config.secretsDir }}"
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-config" $.Release.Name }}
        - name: certs
          secret:
            secretName: {{ printf "%s-server-cert" $.Release.Name }}
        - name: secret
          secret:
            secretName: {{ printf "%s-secret" $.Release.Name }}
{{- end }}