{{ include "baseResources.service" (dict "root" $ "vals" .Values.app) }}
---
{{ include "baseResources.httproute" (dict "root" $ "vals" .Values.app) }}
---
{{ include "baseResources.internalTLS" (dict "root" $ "vals" .Values.app) }}
---
{{ include "redis.resources" (dict "root" $ "vals" .Values.redis) }}
---
{{ include "mariadb.resources" (dict "root" $ "vals" .Values.database) }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component | quote }}
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name | default $.Chart.Name | quote }}
      app.kubernetes.io/component: {{ .component | quote }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component | quote }}

    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false

      initContainers:
        {{- include "baseResources.waitForMariadb" $.Values.database | nindent 8 }}
        {{- include "baseResources.waitForRedis" (dict
            "host" (include "redis.serviceFQDN" (dict "root" $))
            "password" $.Values.redis.password) | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" . ) | indent 8 }}

          command:
            - authelia
          args:
            - "--config=/config/configuration.yml"
            - "--config=/config/configuration.clients.yml"
            - "--config=/config/configuration.acl.yml"

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name | quote }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name | quote }}

          volumeMounts:
            - name: config
              mountPath: /config
            - name: certs
              mountPath: /tmp/certs
              readOnly: true
            - name: secrets
              mountPath: {{ $.Values.config.secretsDir | quote }}
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-config" $.Release.Name | quote }}
        - name: certs
          secret:
            secretName: {{ printf "%s-server-cert" $.Release.Name | quote }}
        - name: secrets
          secret:
            secretName: {{ printf "%s-secret" $.Release.Name | quote }}
{{- end }}