{{- $serviceName := include "baseResources.serviceName" (dict "root" $ "vals" .Values.app) }}

# Traefik middleware to proxy things through Authelia
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "authelia-forward-auth"
  namespace: "traefik"
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: {{ printf "https://%s.%s.svc:9091/api/authz/forward-auth" $serviceName .Release.Namespace | quote }}
    tls:
      #certSecret: "cluster-ca"
      insecureSkipVerify: true
    trustForwardHeader: false
    maxResponseBodySize: 1048576
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
      - "Remote-Name"
      - "Remote-Email"
    authRequestHeaders:
      - "Cookie"
      - "Authorization"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "authelia-status-rewrite"
  namespace: "traefik"
spec:
  plugin:
    traefikerrorreplace:
      matchStatus:
        - 401
      replaceStatus: 302