{{- $root := . -}}
{{- $config := $root.Values.config -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" $root.Release.Name | quote }}
  labels:
    {{- include "common.labels" $root | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
type: Opaque
stringData:
  JWT_SECRET: {{ $config.jwtSecret | quote }}
  LDAP_PASSWORD: {{ $config.ldap.password | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
  OIDC_HMAC_SECRET: {{ $config.hmacSecret | quote }}
  OIDC_KEY: |-
    {{ $config.oidcKey | nindent 4 }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  SESSION_SECRET: {{ $config.sessionSecret | quote }}
  STORAGE_ENCRYPTION_KEY: {{ $config.storageEncryptionKey | quote }}