apiVersion: v2
name: Authelia
description: A Helm chart for Authelia. The database is handled by a clustered MariaDB deployment.
type: application
version: 0.3.0
appVersion: "4.39"

dependencies:
  - name: common-labels
    version: 0.1.0
    repository: "file://../library/common-labels"

  - name: default-svc
    version: 0.1.0
    repository: "file://../library/default-svc"

  - name: redis
    version: 0.1.0
    repository: "file://../library/redis"
