app:
  # -- App name
  name: authelia
  # -- Number of pods
  replicaCount: 2

  image:
    # -- App image
    repository: authelia/authelia
    # -- Image version
    tag: 4.39

  # -- Runtime user
  uid: 1001
  # -- Runtime group
  gid: 1001

  resources:
    requests:
      cpu: "500m"
      memory: "128Mi"
    limits:
      memory: "256Mi"

database:
  # -- Kind of database
  type:
  # -- FQDN to database
  host:
  # -- Database deployment name
  instanceName:
  # -- Database namespace
  namespace:
  # -- Database port
  port: 3306
  # -- Database name
  name:
  # -- Database username
  username:
  # -- Database password
  password:

redis:
  # -- Number of redis pods
  replicaCount: 1

  image:
    repository: 11notes/redis
    tag: 7.4.5

  # -- Redis port
  port: 6379

  # -- Redis username
  username: default
  # -- Redis password
  password:

  resources:
    requests:
      cpu: "250m"
      memory: "64Mi"
    limits:
      memory: "256Mi"

  livenessProbe:
    exec:
      command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "ping"]
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    exec:
      command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "ping"]
    initialDelaySeconds: 5
    periodSeconds: 10

service:
  # -- App port
  port: 9091

ingress:
  # -- FQDN to application
  baseUrl:

config:
  # -- Directory to mount secret files in
  secretsDir: /secrets
  jwtSecret:
  sessionSecret:
  storageEncryptionKey:
  hmacSecret:

  # -- PEM-formatted key
  oidcKey: |

  ldap:
    # -- LDAP URL
    url:
    # -- LDAP user
    searchUser:
    # -- LDAP password
    password:
    # -- LDAP search root
    baseDN:
    # -- LDAP user filter
    userFilter:
    # -- LDAP group filter
    groupFilter:
