app:
  # -- Name of the application
  name: postgres-cluster

  # -- Number of replicas to deploy for the application
replicaCount: 3

image:
  # -- Docker image repository for the application
  repository: ghcr.io/tensorchord/cloudnative-vectorchord
  # -- Docker image tag (can be left empty to use the latest version)
  tag: 17.10-1.1.1

certificate:
  domainName: 
  caBundleSecret: invis-external-bundle

pooler:
  lb:
    ip: 

backup:
  enabled: true
  endpointUrl: 
  accessKey: 
  secretKey: 
