replicaCount: 3

image:
  repository: ghcr.io/tensorchord/cloudnative-vectorchord
  tag: 17-0.5.2

certificate:
  domainName:
  caBundleSecret:

database:
  users:
    - name: immich-user
      comment: Immich
    - name: miniflux-user
      comment: Miniflux
    - name: openwebui-user
      comment: Open WebUI
    - name: openwebui-vector-user
      comment: Open WebUI Vector

backup:
  enabled: true
  endpointUrl:
  accessKey:
  secretKey:
