apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "glance" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName | default "glance" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      initContainers:
        - name: init-chown
          image: busybox:1.36
          command: ["sh", "-c", "chown -R {{ .Values.app.uid }}:{{ .Values.app.gid }} /app/assets"]
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: {{ .Release.Name }}-assets
              mountPath: /app/assets
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.app.image.repo }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.network.port }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
          {{- toYaml .Values.app.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: {{ .Values.network.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: {{ .Values.network.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: {{ .Release.Name }}-assets
              mountPath: /app/assets
          {{- range $path, $_ := .Files.Glob "files/*.yml" }}
            - name: {{ $.Release.Name }}-config
              mountPath: /app/config/{{ base $path }}
              subPath: {{ base $path }}
          {{- end }}
      volumes:
        - name: {{ .Release.Name }}-assets
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-assets
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-config
