apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "glance" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data: # Place config files into files directory
{{- range $path, $bytes := .Files.Glob "files/*.yml" }}
  {{ base $path }}: |-
{{ $bytes | toString | indent 4 }}
{{- end }}