{{ include "baseResources.service" (dict "root" $ "vals" .Values.app) }}
---
{{ include "baseResources.httproute" (dict "root" $ "vals" .Values.app) }}
---
{{ include "mariadb.resources" (dict "root" $ "vals" .Values.database) }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component | quote }}
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      app.kubernetes.io/component: {{ .component | quote }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component | quote }}

    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ .gid }}

      initContainers:
        {{- include "baseResources.waitForMariadb" $.Values.database | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | nindent 8 }}

          envFrom:
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name | quote }}
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name | quote }}

          volumeMounts:
            - name: config
              mountPath: /app/vikunja/config.yml
              subPath: config.yml
            - name: files
              mountPath: /app/vikunja/files

      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-config" $.Release.Name | quote }}
            items:
              - key: config.yml
                path: config.yml
        - name: files
          persistentVolumeClaim:
            claimName: {{ printf "%s-files" $.Release.Name | quote }}
{{- end }}