{{ include "baseResources.service" . }}
---
{{ include "baseResources.ingress" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicaCount | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: frontend

  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend

    spec:
      automountServiceAccountToken: false
      containers:
        - {{ include "baseResources.baseContainer" . | nindent 10 }}

          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - secretRef:
                name: {{ print .Release.Name "-secret" | quote }}
            - configMapRef:
                name: {{ print .Release.Name "-env" | quote }}

          {{- with .Values.app.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: configmap
              mountPath: /app/vikunja/config.yml
              subPath: config.yml

      volumes:
        - name: configmap
          configMap:
            name: {{ print .Release.Name "-config" | quote }}
            items:
              - key: config.yml
                path: config.yml