apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
type: Opaque
stringData:
  VIKUNJA_DATABASE_PASSWORD: {{ .Values.database.password | quote }}
  VIKUNJA_AUTH_OPENID_PROVIDERS_OIDC_CLIENTSECRET: {{ .Values.config.oidc.clientSecret | quote }}
  AUTHELIA_SECRET: {{ .Values.config.oidc.clientSecret | quote }}