apiVersion: v1
kind: Secret
metadata:
  name: {{ print .Release.Name "-secret" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.database.password }}"
  OIDC_CLIENT_ID: "{{ .Values.config.oidc.clientId }}"
  OIDC_CLIENT_SECRET: "{{ .Values.config.oidc.clientSecret }}"
  APP_KEY: "{{ .Values.config.appKey }}"
