{{ include "default-svc.service" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: frontend

  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend

    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:17-alpine

        command:
        - sh
        - -c
        - |
          until pg_isready -h {{ .Values.mainDb.host }} -p 5432 -U "{{ .Values.mainDb.owner }}"; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

        securityContext:
          capabilities:
            drop: ["ALL"]
          allowPrivilegeEscalation: false

      containers:
        - name: {{ .Release.Name | quote }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}

          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - configMapRef:
                name: {{ print .Release.Name "-env" | quote }}
            - secretRef:
                name: {{ print .Release.Name "-secret" | quote }}

          {{- with .Values.app.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: "certs"
              mountPath: "/etc/cert"
              readOnly: true

      volumes:
        - name: "certs"
          secret:
            secretName: {{ print .Release.Name "-server-cert" | quote }}