# This requires traefik crds - https://doc.traefik.io/traefik/getting-started/quick-start-with-kubernetes/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-route
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Miniflux
    gethomepage.dev/description: RSS Reader
    gethomepage.dev/icon: si-rss
    gethomepage.dev/href: "https://{{ .Values.ingress.baseUrl }}"
    gethomepage.dev/pod-selector: "app.kubernetes.io/component=frontend"
    gethomepage.dev/group: Frontend
    gethomepage.dev/weight: "10"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.env.baseUrl | replace "https://" "" | replace "http://" "" }}`)
      services:
        - kind: Service
          name: "{{ .Release.Name }}-svc"
          port: {{ .Values.service.port }}
          serversTransport: "{{ .Release.Name }}-transport"
          scheme: https
