apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: "external-transport"
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  serverName: {{ printf "%s." .Values.external.url | quote }}
  insecureSkipVerify: false
  rootCAs:
    - secret: "invis-external-bundle"