{{- range $name, $config := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-external
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "common.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: {{ $name }}
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
      protocol: TCP
---
{{- end }}