apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-lb-pool1
  namespace: metallb-system
spec:
  addresses:
    - 10.40.40.201-10.40.40.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-l2adv
  namespace: metallb-system
