apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  ENABLE_PERSISTENT_CONFIG: "true"
  ENABLE_OAUTH_PERSISTENT_CONFIG: "false"
  ENABLE_LOGIN_FORM: "false"
  ENABLE_SIGNUP: "false"
  ENABLE_OAUTH_SIGNUP: "true"
  ENABLE_PASSWORD_AUTH: "false"
  ENABLE_TITLE_GENERATION: "true"
  ENABLE_MESSAGE_RATING: "false"
  ENABLE_COMMUNITY_SHARING: "false"
  ENABLE_EVALUATION_ARENA_MODELS: "false"
  ENABLE_BASE_MODELS_CACHE: "true"
  LOG_FORMAT: "json"
  MODELS_CACHE_TTL: "30"
  BYPASS_MODEL_ACCESS_CONTROL: "true"
  USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:154.0) Gecko/20100101 Firefox/154.0"

  WEBUI_URL: {{ printf "https://%s" .Values.app.route.baseUrl | quote }}
  CORS_ALLOW_ORIGIN: {{ printf "https://%s" .Values.app.route.baseUrl | quote }}
  PORT: {{ .Values.app.route.port | quote }}
  DOCKER: "true"

  OPENID_PROVIDER_URL: {{ .Values.config.oidc.url | quote }}
  OPENID_END_SESSION_ENDPOINT: {{ .Values.config.oidc.logoutUrl | quote }}
  OAUTH_SCOPES: "openid email profile"
  OPENID_REDIRECT_URI: {{ .Values.config.oidc.redirectUrl | quote }}
  OAUTH_CODE_CHALLENGE_METHOD: "S256"
  ENABLE_OAUTH_GROUP_CREATION: "true"
  OAUTH_UPDATE_NAME_ON_LOGIN: "true"
  OAUTH_UPDATE_EMAIL_ON_LOGIN: "true"