{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}

    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ .gid }}

      containers:
        - {{ include "baseResources.baseContainer" (dict "root" $ "vals" .) | nindent 10 }}

          ports:
            {{- range .service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}

          {{- with .resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          securityContext:
            runAsGroup: {{ .gid }}
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: data
              mountPath: "/app/backend/data"
            - name: static
              mountPath: "/app/backend/open_webui/static"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-data" $.Release.Name }}
        - name: static
          emptyDir: {}
{{- end }}