{{ include "baseResources.service" (dict "root" $ "vals" .Values.app) }}
---
{{ include "baseResources.httproute" (dict "root" $ "vals" .Values.app) }}
---
{{ include "redis.resources" (dict "root" $ "vals" .Values.redis) }}
---
{{ include "cnpg.resources" (dict "root" $ "vals" .Values.mainDb) }}
---
{{ include "cnpg.resources" (dict "root" $ "vals" .Values.vectorDb) }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component | quote }}
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      app.kubernetes.io/component: {{ .component | quote }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component | quote }}

    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ .gid }}

      initContainers:
        {{- include "baseResources.waitForPostgres" $.Values.mainDb | nindent 8 }}
        {{- include "baseResources.waitForRedis" (dict
            "host" (include "redis.serviceFQDN" (dict "root" $))
            "password" $.Values.redis.password) | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name | quote }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name | quote }}

          volumeMounts:
            - name: data
              mountPath: "/app/backend/data"
            - name: static
              mountPath: "/app/backend/open_webui/static"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-data" $.Release.Name | quote }}
        - name: static
          emptyDir: {}
{{- end }}