apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-data" .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
{{- with .Values.storage.data }}
  volumeName: {{ .existingClaim | quote }}
{{- end }}