{{- $redisSvc := include "redis.serviceFQDN" (dict "root" $) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Release.Name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
type: Opaque
stringData:
  WEBUI_SECRET_KEY: {{ required "config.webUI.secretKey is required" .Values.config.webUI.secretKey | quote }}

  DATABASE_TYPE: "postgresql"
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.mainDb.owner .Values.mainDb.password .Values.mainDb.host (int .Values.mainDb.port) .Values.mainDb.name | quote }}
  DATABASE_ENABLE_SESSION_SHARING: "true"

  VECTOR_DB: "pgvector"
  PGVECTOR_CREATE_EXTENSION: "false"
  PGVECTOR_DB_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.vectorDb.owner .Values.vectorDb.password .Values.vectorDb.host (int .Values.vectorDb.port) .Values.vectorDb.name | quote }}

  REDIS_URL: {{ printf "redis://%s:%s@%s:%d" .Values.redis.username .Values.redis.password $redisSvc .Values.redis.port | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}

  OAUTH_CLIENT_ID: {{ required "config.oidc.clientId is required" .Values.config.oidc.clientId | quote }}
  OAUTH_CLIENT_SECRET: {{ required "config.oidc.clientSecret is required" .Values.config.oidc.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-credentials" .Values.vectorDb.owner | lower | quote }}
  namespace: {{ .Values.vectorDb.namespace | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: {{ .Values.vectorDb.owner | quote }}
    password: {{ .Values.vectorDb.password | quote }}