apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-smb-credentials" .Release.Name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  namespace: kube-system
type: Opaque
stringData:
  username: {{ .Values.storage.smb.username | quote }}
  password: {{ .Values.storage.smb.password | quote }}