apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print .Release.Name "-configmap" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  navidrome.toml: |
    LogLevel = 'info'
    EnableInsightsCollector = 'false'
    BaseUrl = 'https://{{ .Values.ingress.baseUrl }}'
    ExtAuth.TrustedSources = '{{ .Values.config.trustedSources }}'
    ExtAuth.UserHeader = 'Remote-User'

    LastFM.Enabled = 'true'
    Deezer.Enabled = 'true'
    ListenBrainz.Enabled = 'false'
    Agents = 'deezer,lastfm'
    LastFM.Language = 'en'

    EnableTranscodingCancellation = 'true'
    EnableCoverAnimation = 'true'
    EnableSharing = 'false'
    DefaultTheme = 'nord'
    AutoImportPlaylists = 'true'
    SessionTimeout = '48h'
    EnableStarRating = 'false'
    Scanner.Enabled = 'true'
    Scanner.WatcherWait = '5s'
    Scanner.ScanOnStartup = 'true'
