{{ include "baseResources.service" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicaCount | default 1 }}
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: frontend

  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ .Values.app.gid }}

      initContainers:
        - {{ include "baseResources.waitForSamba" . | nindent 10 }}

      containers:
        - {{ include "baseResources.baseContainer" . | nindent 10 }}

          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - secretRef:
                name: {{ print .Release.Name "-secret" | quote }}
          env:
            - name: ND_CONFIGFILE
              value: /data/navidrome.toml

          {{- with .Values.app.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: config-pvc
              mountPath: /data
            - name: config
              mountPath: /data/navidrome.toml
              subPath: navidrome.toml
              readOnly: true
            - name: music
              mountPath: /music
              readOnly: true
            - name: cache
              mountPath: /data/cache

      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: {{ print .Release.Name "-config-pvc" | quote }}
        - name: config
          configMap:
            name: {{ print .Release.Name "-configmap" | quote }}
            items:
              - key: navidrome.toml
                path: navidrome.toml
        - name: music
          persistentVolumeClaim:
            claimName: {{ print .Release.Name "-music" | quote }}
        - name: cache
          emptyDir:
            medium: Memory
