{{- with .Values.app }}
{{ include "baseResources.service" (dict "root" $ "vals" .) }}
{{- end }}
---
{{- with .Values.app.route }}
{{ include "baseResources.httproute" (dict "root" $ "vals" . ) }}
{{- end }}
---
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ .gid }}

      initContainers:
        {{- include "baseResources.waitForSamba" $.Values.storage.smb | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          ports:
            {{- range .service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}

          envFrom:
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}
          env:
            - name: ND_CONFIGFILE
              value: /data/navidrome.toml

          volumeMounts:
            - name: config-pvc
              mountPath: /data
            - name: config
              mountPath: /data/navidrome.toml
              subPath: navidrome.toml
              readOnly: true
            - name: music
              mountPath: /music
              readOnly: true
            - name: cache
              mountPath: /data/cache

      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: {{ printf "%s-config-pvc" $.Release.Name }}
        - name: config
          configMap:
            name: {{ printf "%s-configmap" $.Release.Name }}
            items:
              - key: navidrome.toml
                path: navidrome.toml
        - name: music
          persistentVolumeClaim:
            claimName: {{ printf "%s-music" $.Release.Name }}
        - name: cache
          emptyDir:
            medium: Memory
{{- end }}