apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
type: Opaque
stringData:
  ND_LASTFM_APIKEY: {{ .Values.config.lastFM.apiKey | quote }}
  ND_LASTFM_SECRET: {{ .Values.config.lastFM.apiSecret | quote }}