apiVersion: v2
name: Miniflux
description: A helm chart for Miniflux RSS-reader. Connecting to a clustered CNPG postgres database.
type: application
version: 0.1.0
appVersion: "2"

dependencies:
  - name: common-labels
    version: 0.1.0
    repository: "file://../library/common-labels"

  - name: default-svc
    version: 0.1.0
    repository: "file://../library/default-svc"

  - name: cnpg-database
    version: 0.1.0
    repository: "file://../library/cnpg-database"
    alias: mainDb
