apiVersion: v2
name: miniflux
description: Basic helm template for Miniflux RSS-reader
type: application
version: 0.1.0
appVersion: "2"

dependencies:
  - name: _templates
    version: "0.1.0"
    repository: "file://../_templates"
