apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Values.mariadb.host }}"
  DB_NAME: "{{ .Values.mariadb.name }}"
  DB_PORT: "{{ .Values.mariadb.port }}"
  DB_SSL_CA: "{{ .Values.mariadb.sslCa }}"
  DB_USER: "{{ .Values.mariadb.user }}"
  DISABLE_RUFFLE_RS: "true"
  DISABLE_USERPASS_LOGIN: "true"
  ENABLE_SCHEDULED_RESCAN: "true"
  OIDC_ENABLED: "true"
  OIDC_PROVIDER: "Authelia"
  OIDC_REDIRECT_URI: "{{ .Values.config.oidc.redirectUri }}"
  OIDC_SERVER_APPLICATION_URL: "{{ .Values.config.oidc.serverApplicationUrl }}"
  OIDC_TLS_CACERTFILE: "{{ .Values.config.oidc.tlsCaCertFile }}"
  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "{{ .Values.redis.port }}"
  ROMM_BASE_URL: "https://{{ .Values.ingress.baseUrl }}"
  ROMM_DB_DRIVER: "{{ .Values.config.dbDriver }}"
  SCHEDULED_RESCAN_CRON: "0 5 * * *"
  HASHEOUS_API_ENABLED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data: 
  config.yml: |
    exclude:
      platforms: []
      roms:
        single_file:
          extensions: []
          names: []
        multi_file:
          names: []
          parts:
            names: []
            extensions: []
    system:
      platforms: {}
      versions: {}
    filesystem: {}