apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Values.database.host }}"
  DB_NAME: "{{ .Values.database.name }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_USER: "{{ .Values.database.username }}"
  DB_QUERY_JSON: '{"ssl": "true"}'
  DISABLE_RUFFLE_RS: "true"
  DISABLE_USERPASS_LOGIN: "true"
  ENABLE_SCHEDULED_RESCAN: "true"
  OIDC_ENABLED: "true"
  OIDC_PROVIDER: "Authelia"
  OIDC_REDIRECT_URI: "{{ .Values.config.oidc.redirectUri }}"
  OIDC_SERVER_APPLICATION_URL: "{{ .Values.config.oidc.serverApplicationUrl }}"
  OIDC_TLS_CACERTFILE: "{{ .Values.config.oidc.tlsCaCertFile }}"
  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "{{ .Values.redis.port }}"
  ROMM_BASE_URL: "https://{{ .Values.ingress.baseUrl }}"
  ROMM_DB_DRIVER: "{{ .Values.database.type }}"
  SCHEDULED_RESCAN_CRON: "0 5 * * *"
  HASHEOUS_API_ENABLED: "true"
  HLTB_API_ENABLED: "true"
  ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: "true"