apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: mariadb:11
          command: 
            - sh
            - -c
            - >
              until mariadb-admin ping -h "${DB_HOST}" -u"${DB_USER}" -p"${DB_PASSWORD}" -s;
              do echo "Waiting for MariaDB..."; sleep 3;
              done
          env:
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_USER
              value: "{{ .Values.database.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.database.password }}"
        - name: wait-for-samba
          image: alpine:3.20
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache samba-client > /dev/null
              echo "Waiting for SMB share "//${SMB_URL}/${SMB_SHARE}"..."
              until smbclient -L "//${SMB_URL}" -U "${SMB_USER}%${SMB_PASS}" -m SMB3 >/dev/null 2>&1; do
                echo "Samba share not ready yet, retrying..."
                sleep 5
              done
              echo "Samba share is available."
          env:
            - name: SMB_URL
              value: "{{ .Values.storage.smb.url }}"
            - name: SMB_SHARE
              value: "{{ .Values.storage.smb.share }}"
            - name: SMB_USER
              value: "{{ .Values.storage.smb.username }}"
            - name: SMB_PASS
              value: "{{ .Values.storage.smb.password }}"
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-env"
            - secretRef:
                name: "{{ .Release.Name }}-secret"
          resources:
          {{- toYaml ( .Values.app.resources | default dict ) | nindent 12 }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/heartbeat
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /api/heartbeat
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: {{ .Release.Name }}-assets
              mountPath: /romm/assets
            - name: {{ .Release.Name }}-games
              mountPath: /romm/library
            - name: {{ .Release.Name }}-resources
              mountPath: /romm/resources
            - name: {{ .Release.Name }}-config
              mountPath: /romm/config
            - name: authelia-fullchain
              mountPath: "{{ .Values.config.oidc.tlsCaCertFile }}"
              subPath: "{{ .Values.config.oidc.tlsCaCertFile | base }}"
      volumes:
        - name: {{ .Release.Name }}-assets
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-assets
        - name: {{ .Release.Name }}-games
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-games
        - name: {{ .Release.Name }}-resources
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-resources
        - name: {{ .Release.Name }}-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: authelia-fullchain
          configMap:
            name: authelia-fullchain
            items:
              - key: "{{ .Values.config.oidc.tlsCaCertFile | base }}"
                path: "{{ .Values.config.oidc.tlsCaCertFile | base }}"
      enableServiceLinks: false
