apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.app.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            runAsUser: {{ .Values.app.uid }}
            runAsGroup: {{ .Values.app.gid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
          {{- toYaml ( .Values.app.resources | default dict ) | nindent 12 }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/heartbeat
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /api/heartbeat
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: {{ .Release.Name }}-assets
              mountPath: /romm/assets
            - name: {{ .Release.Name }}-games
              mountPath: /romm/library
            - name: {{ .Release.Name }}-resources
              mountPath: /romm/resources
            - name: {{ .Release.Name }}-config
              mountPath: /romm/config
            - name: authelia-fullchain
              mountPath: {{ .Values.config.oidc.tlsCaCertFile }}
              subPath: {{ .Values.config.oidc.tlsCaCertFile | base }}
      volumes:
        - name: {{ .Release.Name }}-assets
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-assets
        - name: {{ .Release.Name }}-games
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-games
        - name: {{ .Release.Name }}-resources
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-resources
        - name: {{ .Release.Name }}-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: authelia-fullchain
          configMap:
            name: authelia-fullchain
            items:
              - key: {{ .Values.config.oidc.tlsCaCertFile | base }}
                path: {{ .Values.config.oidc.tlsCaCertFile | base }}
      enableServiceLinks: false
