apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-games" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: {{ print .Release.Name "-games" | quote }}
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-assets" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.assets.size }}
{{- with .Values.storage.assets }}
  volumeName: {{ .volumeName | quote }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-resources" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.resources.size }}
{{- with .Values.storage.resources }}
  volumeName: {{ .volumeName | quote }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-config" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
{{- with .Values.storage.config }}
  volumeName: {{ .volumeName | quote }}
{{- end }}