apiVersion: v1
kind: Secret
metadata:
  name: {{ print .Values.mainDb.owner "-credentials" | quote }}
  namespace: {{ .Values.mainDb.namespace | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: {{ required "mainDb.owner is required" .Values.mainDb.owner | quote }}
    password: {{ required "mainDb.password is required" .Values.mainDb.password | quote }}