{{- if .Values.mariadb.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ .Release.Name }}-user
  labels:
    {{- include "common.labels" (dict "Values" .Values "Chart" .Chart "Release" .Release "kind" "Deployment") | nindent 4 }}
spec:
  name: {{ .Release.Name }}-user
  mariaDbRef:
    name: db-{{ .Release.Name }}
  passwordSecretKeyRef:
    name: {{ .Release.Name }}-secret
    key: DB_PASSWORD
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
{{- end }}