---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "authelia" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  AUTHELIA_DEFAULT_2FA_METHOD: "totp"
  AUTHELIA_THEME: "auto"
  AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: /tmp/notifications.txt
  AUTHELIA_NTP_ADDRESS: "udp://pool.ntp.org:123"
  X_AUTHELIA_CONFIG_FILTERS: "template"

  AUTHELIA_SERVER_ADDRESS: "tcp4://0.0.0.0:9091/"
  AUTHELIA_CERTIFICATES_DIRECTORY: "/tmp/certs"
  AUTHELIA_SERVER_TLS_CERTIFICATE: "/tmp/certs/tls.crt"
  AUTHELIA_SERVER_TLS_KEY: "/tmp/certs/tls.key"

  AUTHELIA_LOG_LEVEL: "info"
  AUTHELIA_LOG_FORMAT: "text"
  AUTHELIA_LOG_KEEP_STDOUT: "true"
  AUTHELIA_LOG_FILE_PATH: "/tmp/authelia.log"

  AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY: "deny"
  AUTHELIA_PASSWORD_POLICY_ZXCVBN_ENABLED: "true"
  AUTHELIA_PASSWORD_POLICY_ZXCVBN_MIN_SCORE: "3"
  AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_CHANGE_DISABLE: "false"
  AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE: "false"

  AUTHELIA_PRIVACY_POLICY_ENABLED: "true"
  AUTHELIA_PRIVACY_POLICY_POLICY_URL: "https://i.imgur.com/4GfOIRb.jpeg"
  AUTHELIA_PRIVACY_POLICY_REQUIRE_USER_ACCEPTANCE: "true"

  AUTHELIA_TOTP_ISSUER: "Auth TOTP"
  AUTHELIA_TOTP_DISABLE: "false"
  AUTHELIA_TOTP_ALGORITHM: "SHA1"
  AUTHELIA_TOTP_DIGITS: "6"
  AUTHELIA_TOTP_PERIOD: "30"
  AUTHELIA_TOTP_SECRET_SIZE: "32"
  AUTHELIA_TOTP_SKEW: "1"
  AUTHELIA_TOTP_DISABLE_REUSE_SECURITY_POLICY: "false"

  AUTHELIA_DUO_API_DISABLE: "true"

  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION: "freeipa"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS: "ldap://{{ .Values.app.ldap.url }}"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_START_TLS: "true"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TLS_SKIP_VERIFY: "false"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TLS_SERVER_NAME: "{{ .Values.app.ldap.url }}"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TIMEOUT: "5 minutes"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TLS_MINIMUM_VERSION: "TLS1.2"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: "{{ .Values.app.secretsDir }}/LDAP_PASSWORD"

  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_USERNAME: "uid"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_DISPLAY_NAME: "displayName"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_DISTINGUISHED_NAME: "distinguishedName"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_GROUP_NAME: "cn"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_MAIL: "mail"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_MEMBER_OF: "memberOf"

  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "{{ .Values.app.ldap.searchUser }},{{ .Values.app.ldap.baseDN }}"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: "{{ .Values.app.ldap.baseDN }}"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER: "{{ .Values.app.ldap.userFilter }}"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN: "cn=users,cn=accounts"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER: "{{ .Values.app.ldap.groupFilter }}"
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN: "cn=groups,cn=accounts"

  AUTHELIA_SESSION_NAME: "auth_cookie"
  AUTHELIA_SESSION_SAME_SITE: "lax"
  AUTHELIA_SESSION_INACTIVITY: "5 minutes"
  AUTHELIA_SESSION_EXPIRATION: "1 hour"
  AUTHELIA_SESSION_REMEMBER_ME: "14 days"
  AUTHELIA_SESSION_SECRET_FILE: "{{ .Values.app.secretsDir }}/SESSION_SECRET"

  AUTHELIA_SESSION_REDIS_HOST: "{{ .Release.Name }}-redis"
  AUTHELIA_SESSION_REDIS_PORT: "{{ .Values.redis.port }}"
  AUTHELIA_SESSION_REDIS_USERNAME: "{{ .Values.redis.user }}"
  AUTHELIA_SESSION_REDIS_PASSWORD_FILE: "{{ .Values.app.secretsDir }}/REDIS_PASSWORD"
  #AUTHELIA_SESSION_REDIS_TLS_MINIMUM_VERSION: "TLS1.2"

  AUTHELIA_STORAGE_MYSQL_ADDRESS: "tcp4://db-{{ .Release.Name }}:{{ .Values.db.port }}"
  AUTHELIA_STORAGE_MYSQL_USERNAME: "{{ .Release.Name }}-user"
  AUTHELIA_STORAGE_MYSQL_DATABASE: "{{ .Release.Name }}-db"
  AUTHELIA_STORAGE_MYSQL_TIMEOUT: "5 seconds"
  AUTHELIA_STORAGE_MYSQL_TLS_SERVER_NAME: "db-{{ .Release.Name }}"
  AUTHELIA_STORAGE_MYSQL_TLS_SKIP_VERIFY: "false"
  AUTHELIA_STORAGE_MYSQL_TLS_MINIMUM_VERSION: "TLS1.2"
  AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE: "{{ .Values.app.secretsDir }}/MYSQL_PASSWORD"
  AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "{{ .Values.app.secretsDir }}/STORAGE_ENCRYPTION_KEY"

  AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_ALGORITHM: "HS256"
  AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_LIFESPAN: "5 minutes"
  AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "{{ .Values.app.secretsDir }}/JWT_SECRET"
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: "{{ .Values.app.secretsDir }}/OIDC_HMAC_SECRET"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.appName | default "authelia" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data: # Place config files into files directory
{{- range $path, $bytes := .Files.Glob "files/*.yml" }}
  {{ base $path }}: |-
{{ $bytes | toString | indent 4 }}
{{- end }}