app:
  # -- Name of the application
  name: mariadb-galera
  # -- Number of replicas to deploy for the application
  replicaCount: 3

  rootPassword: 

maxScale:
  # -- Name of the application
  name: maxscale

  adminUsername: 
  adminPassword: 

  service:
    nameOverride: 
    type: LoadBalancer
    loadBalancerIP: 

  route:
    # -- Base URL for the service
    baseUrl: 
    # -- Port used for the route
    port: 8989
    rules:
      - path: /

backup:
  schedule: "0 23 * * *"

  endpoint: 
  accessKey: 
  secretKey: 
