{
 "title": "Kubernetes Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(kubelet_node_name,instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "__auto" },
    { "expr": "kube_node_spec_taint", "legendFormat": "__auto" },
    { "expr": "kube_node_role", "legendFormat": "__auto" },
    {
     "expr": "kube_node_status_condition{status=\"true\"} == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (node) (kube_pod_info{node!=\"\"}) \r\n/ \r\non(node) kube_node_status_capacity{resource=\"pods\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kube_pod_container_resource_requests{resource=\"cpu\", namespace!=\"\"}) / sum by(node) (kube_node_status_allocatable{resource=\"cpu\"})\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node)(\r\n  label_replace(rate(container_cpu_usage_seconds_total{container!=\"\", image!=\"\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*)\")\r\n)\r\n/\r\nsum by(node)(\r\n  kube_node_status_allocatable{resource=\"cpu\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node)(\r\n  kube_pod_container_resource_requests{resource=\"memory\", namespace!=\"\"}\r\n)\r\n/\r\nsum by(node)(\r\n  kube_node_status_allocatable{resource=\"memory\"}\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (\r\n  label_replace(\r\n    container_memory_working_set_bytes{\r\n      container!=\"\",\r\n      image!=\"\",\r\n      pod!=\"\",\r\n    },\r\n    \"node\",\r\n    \"$1\",\r\n    \"instance\",\r\n    \"(.*)\"\r\n  )\r\n)\r\n/\r\nsum by(node) (kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{instance=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node)(\r\n  label_replace(rate(container_cpu_usage_seconds_total{container!=\"\", image!=\"\", instance=~\"$nodes\", namespace=~\"$namespace\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*)\")\r\n)\r\n/\r\nsum by(node)(\r\n  kube_node_status_allocatable{resource=\"cpu\", node=~\"$nodes\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Req",
   "type": "stat",
   "description": "CPU Requests",
   "gridPos": { "h": 4, "w": 1, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace!=\"\", node=~\"$nodes\", namespace=~\"$namespace\"}\r\n)\r\n/\r\nsum(\r\n  kube_node_status_allocatable{resource=\"cpu\", node=~\"$nodes\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "table",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{\r\n  namespace=~\"$namespace\",\r\n  phase!=\"Succeeded\"\r\n} == 1\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod) (\r\n  increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[$__range])\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod)(\r\n  rate(container_cpu_usage_seconds_total{container!=\"\", image!=\"\"}[5m])\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod)(\r\n  container_memory_working_set_bytes{container!=\"\", image!=\"\"}\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod) (\r\n  (rate(container_network_receive_bytes_total{interface!=\"lo\"}[5m])\r\n   +\r\n   rate(container_network_transmit_bytes_total{interface!=\"lo\"}[5m])\r\n  ) * 8\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace, pod, node, pod_ip) (kube_pod_info{namespace=~\"$namespace\", node=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  container_memory_working_set_bytes{\r\n    container!=\"\",\r\n    image!=\"\",\r\n    pod!=\"\",\r\n    namespace=~\"$namespace\",\r\n    instance=~\"$nodes\"\r\n  }\r\n)\r\n",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"memory\", node=~\"$nodes\"}",
     "legendFormat": "{{node}} Limit"
    }
   ]
  },
  {
   "title": "RAM Req",
   "type": "stat",
   "description": "Memory Requests",
   "gridPos": { "h": 4, "w": 1, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_resource_requests{resource=\"memory\", namespace!=\"\", node=~\"$nodes\", namespace=~\"$namespace\"}\r\n)\r\n/\r\nsum(\r\n  kube_node_status_allocatable{resource=\"memory\", node=~\"$nodes\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pod RAM Limit",
   "type": "timeseries",
   "description": "How close a pod is to their memory limit",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  100 *\r\n  sum by (namespace, pod) (\r\n    container_memory_working_set_bytes{container!=\"\", image!=\"\", namespace=~\"$namespace\", instance=~\"$nodes\"}\r\n  )\r\n  /\r\n  sum by (namespace, pod) (\r\n    kube_pod_container_resource_limits{resource=\"memory\"}\r\n  )\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\r\n  rate(container_network_receive_bytes_total{\r\n    instance=~\"$nodes\",\r\n    namespace=~\"$namespace\"\r\n  }[5m]) * 8\r\n)\r\n",
     "legendFormat": "RX {{pod}}"
    },
    {
     "expr": "sum by(namespace, pod) (\r\n  rate(container_network_transmit_bytes_total{\r\n    instance=~\"$nodes\",\r\n    namespace=~\"$namespace\"\r\n  }[5m]) * 8 * -1\r\n)\r\n",
     "legendFormat": "TX {{pod}}"
    },
    {
     "expr": "sum(\r\n  rate(container_network_receive_bytes_total{\r\n    instance=~\"$nodes\",\r\n    namespace=~\"$namespace\"\r\n  }[5m]) * 8\r\n)\r\n",
     "legendFormat": "RX Total"
    },
    {
     "expr": "sum(\r\n  rate(container_network_transmit_bytes_total{\r\n    instance=~\"$nodes\",\r\n    namespace=~\"$namespace\"\r\n  }[5m]) * 8 * -1\r\n)\r\n",
     "legendFormat": "TX Total"
    }
   ]
  }
 ]
}