app:
  # -- Name of the application
  name: openwebui
  # -- Component of the application being configured (e.g., frontend, backend)
  component: frontend
  # -- Number of replicas to deploy for the application
  replicaCount: 1

  image:
    # -- Docker image repository for the application
    repository: ghcr.io/open-webui/open-webui
    # -- Docker image tag (can be left empty to use the latest version)
    tag: v0.11.3
    pullPolicy: IfNotPresent

  # -- User ID for the container
  uid: 1001
  # -- Group ID for the container
  gid: 1001

  livenessProbe:
    httpGet:
      # -- Protocol used for the liveness probe
      scheme: HTTP
      # -- Path to the health check endpoint
      path: /health
      # -- Port used for the liveness probe
      port: 3000
    # -- Delay before starting the liveness probe
    initialDelaySeconds: 15
    # -- Frequency of the liveness probe
    periodSeconds: 10

  readinessProbe:
    httpGet:
      # -- Protocol used for the readiness probe
      scheme: HTTP
      # -- Path to the health check endpoint
      path: /health
      # -- Port used for the readiness probe
      port: 3000
    # -- Delay before starting the readiness probe
    initialDelaySeconds: 2
    # -- Frequency of the readiness probe
    periodSeconds: 5

  service:
    ports: 
    - name: http
      # -- Port exposed by the service
      port: 3000
      # -- Port the container is listening on
      targetPort: 3000
      # -- Protocol used for the service
      protocol: TCP

  route:
    # -- Base URL for the service
    baseUrl: 
    # -- Port used for the route
    port: 3000
    rules:
      - path: /

mainDb:
  # -- Fully qualified domain name (FQDN) to the database
  host: 
  # -- Port used to connect to the database
  port: 5432
  # -- Name of the database
  name: 

  # -- Kubernetes namespace where the database is deployed
  namespace: 
  clusterName: 
  # -- Username used to connect to the database
  owner: 
  # -- Password used to connect to the database
  password: 

vectorDb:
  # -- Fully qualified domain name (FQDN) to the database
  host: 
  # -- Port used to connect to the database
  port: 5432
  # -- Name of the database
  name: 

  # -- Kubernetes namespace where the database is deployed
  namespace: 
  clusterName: 
  # -- Username used to connect to the database
  owner: 
  # -- Password used to connect to the database
  password: 

  extensions:
    - name: vector
      ensure: present

redis:
  replicaCount: 1
  port: 6379
  username: default
  password: 

storage:
  data:
    existingClaim: pvc-c5696362-71b0-4e92-b277-234bf531c5a6

config:
  webUI:
    admin:
      name: 
      password: 
    secretKey: 

  oidc:
    url: 
    logoutUrl: 
    redirectUrl: 
    clientId: openwebui
    clientSecret: 