app:
  name: 

victoriametrics:
  name: 
  image:
    tag: v1.131.0-cluster

  ingress:
    baseUrl: 

  graphite:
    metallb:
      ip: 

vmagent:
  remoteWriteUrl: 

blackbox:
  name: blackbox
  image:
    repository: prom/blackbox-exporter
    tag: master-distroless

  uid: 
  gid: 

  service:
    port: 