app:
  name: 

victoriametrics:
  name: 
  image:
    tag: v1.131.0-cluster

  ingress:
    baseUrl: 

  graphite:
    metallb:
      ip: 

vmagent:
  remoteWriteUrl: 

blackbox:
  name: blackbox
  image:
    repository: prom/blackbox-exporter
    tag: master-distroless

  uid: 
  gid: 

  service:
    port: 

  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      memory: "100Mi"

  livenessProbe:
    httpGet:
      path: /health
      port: 9115
    initialDelaySeconds: 10
    periodSeconds: 15

  readinessProbe:
    httpGet:
      path: /health
      port: 9115
    initialDelaySeconds: 2
    periodSeconds: 5