apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  VIKUNJA_SERVICE_PUBLICURL: "https://{{ .Values.ingress.baseUrl }}"
  VIKUNJA_DATABASE_HOST: "{{ .Values.database.host }}"
  VIKUNJA_DATABASE_TYPE: "{{ .Values.database.type }}"
  VIKUNJA_DATABASE_USER: "{{ .Values.database.username }}"
  VIKUNJA_DATABASE_DATABASE: "{{ .Values.database.name }}"
  VIKUNJA_DATABASE_TLS: "skip-verify"
  VIKUNJA_AUTH_LOCAL_ENABLED: "false"
  VIKUNJA_AUTH_OPENID_ENABLED: "true"
  VIKUNJA_AUTH_OPENID_PROVIDERS_OIDC_NAME: "OIDC"
  VIKUNJA_AUTH_OPENID_PROVIDERS_OIDC_AUTHURL: "{{ .Values.config.oidc.url }}"
  VIKUNJA_AUTH_OPENID_PROVIDERS_OIDC_LOGOUTURL: "{{ .Values.config.oidc.url }}/logout"
  VIKUNJA_AUTH_OPENID_PROVIDERS_OIDC_CLIENTID: "{{ .Values.config.oidc.clientID }}"
  VIKUNJA_AUTH_OPENID_PROVIDERS_OIDC_SCOPE: "openid email profile"
  VIKUNJA_DEFAULTSETTINGS_WEEK_START: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yml: |
    auth:
      openid:
        providers:
          - OIDC