{{- range $name, $config := .Values.services }}
# This requires traefik crds - https://doc.traefik.io/traefik/getting-started/quick-start-with-kubernetes/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-route
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: {{ $name | title }}
    gethomepage.dev/description: {{ $config.homepage.description }}
    gethomepage.dev/icon: {{ $config.homepage.icon }}
    gethomepage.dev/href: "https://{{ $name }}.{{ $.Values.domain }}"
    gethomepage.dev/group: Containers
    gethomepage.dev/weight: "{{ $config.homepage.weight }}"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ $name }}.{{ $.Values.domain }}`)
      services:
        - kind: Service
          name: {{ $.Release.Name }}-{{ $name }}-external
          port: {{ $config.port }}
          scheme: {{ $config.scheme }}
          {{- if eq $config.scheme "https"}}
          serversTransport: external-transport
          {{- end }}
      middlewares:
        - name: authelia-forward-auth
          namespace: traefik
---
{{- end }}