app:
  # -- Name of the application
  name: glance
  # -- Number of replicas to deploy for the application
  replicaCount: 1
  # -- Component of the application being configured (e.g., frontend, backend)
  component: frontend

  image:
    # -- Docker image repository for the application
    repository: glanceapp/glance
    # -- Docker image tag (can be left empty to use the latest version)
    tag: v0.8.6
    pullPolicy: Always

    # -- User ID for the container
  uid: 1001
    # -- Group ID for the container
  gid: 1001

  resources:
    requests:
      # -- Minimum CPU resources required by the container
      cpu: "250m"
      # -- Minimum memory resources required by the container
      memory: "64Mi"
    limits:
      # -- Maximum memory resources allowed for the container
      memory: "256Mi"

  livenessProbe:
    httpGet:
      # -- Protocol used for the liveness probe
      scheme: HTTP
      # -- Path to the health check endpoint
      path: /
      # -- Port used for the liveness probe
      port: 8080
    # -- Delay before starting the liveness probe
    initialDelaySeconds: 15
    # -- Frequency of the liveness probe
    periodSeconds: 10

  readinessProbe:
    httpGet:
      # -- Protocol used for the readiness probe
      scheme: HTTP
      # -- Path to the health check endpoint
      path: /
      # -- Port used for the readiness probe
      port: 8080
    # -- Delay before starting the readiness probe
    initialDelaySeconds: 2
    # -- Frequency of the readiness probe
    periodSeconds: 5

  service:
    ports: 
    - name: http
      # -- Port exposed by the service
      port: 8080
      # -- Port the container is listening on
      targetPort: 8080
      # -- Protocol used for the service
      protocol: TCP

  route:
    # -- Base URL for the service
    baseUrl: 
    # -- Port used for the route
    port: 8080
    rules:
      - name: root
        path: /
        statusRewrite: true
        forwardAuth: true