app:
  # -- App name
  name: immich
  # -- Number of pods
  replicaCount: 1

  image:
    # -- App image
    repository: ghcr.io/immich-app/immich-server
    # -- Image version
    tag: release
    # -- Image pull policy
    pullPolicy: Always

  # -- Runtime user
  uid:
  # -- Runtime group
  gid:

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      memory: "2Gi"

redis:
  # -- Number of redis pods
  replicaCount: 1

  image:
    # -- Redis image
    repository: 11notes/redis
    # -- Redis image version
    tag: 7.4.5

  resources:
    requests:
      cpu: "250m"
      memory: "64Mi"
    limits:
      memory: "256Mi"

  # -- Redis username
  user: default
  # -- Redis password
  password:
  # -- Redis port
  port: 6379

database:
  # -- Database URL
  host:
  # -- Database namespace
  namespace:
  # -- Database name
  name:
  # -- Database username
  username:
  # -- Database password
  password:

storage:
  smb:
    # -- Samba share URL
    url:

service:
  # -- App port
  port: 2283

ingress:
  # -- FQDN for the application
  baseUrl:

config:
  machineLearning:
    url:

  # -- Samba username
  smbUser:
  # -- Samba password
  smbPassword:
