apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  TZ: "Europe/Stockholm"
  TEMP_DIR: "/app/temp_audio"

  {{- with .Values.mainDb }}
  POSTGRES_USER: {{ .owner | quote }}
  POSTGRES_DB: {{ .name | quote }}
  POSTGRES_HOST: {{ .host | quote }}
  POSTGRES_PORT: {{ .port | quote }}
  {{- end }}