apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" .Release.Name | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
data:
  TZ: "Europe/Stockholm"
  TEMP_DIR: "/app/temp_audio"