{{ include "baseResources.service" (dict "root" $ "vals" .Values.frontend) }}
---
{{ include "baseResources.httproute" (dict "root" $ "vals" .Values.frontend) }}
---
{{ include "redis.resources" (dict "root" $ "vals" .Values.redis) }}
---
{{ include "cnpg.resources" (dict "root" $ "vals" .Values.mainDb) }}
---
{{- with .Values.frontend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baseResources.resourceName" (dict "root" $ "vals" .) }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ int64 .gid }}

      initContainers:
        {{- include "baseResources.waitForPostgres" $.Values.mainDb | nindent 8 }}
        {{- include "baseResources.waitForRedis" (dict
            "host" (include "redis.serviceFQDN" (dict "root" $))
            "password" $.Values.redis.password) | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}

          env:
          - name: SERVICE_TYPE
            value: "flask"

          volumeMounts:
            - name: flask-temp
              mountPath: /app/temp_audio

      volumes:
        - name: flask-temp
          emptyDir: {}
{{- end }}
---
{{- with .Values.worker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baseResources.resourceName" (dict "root" $ "vals" .) }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .component }}

  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ .component }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: {{ int64 .gid }}

      initContainers:
        {{- include "baseResources.waitForPostgres" $.Values.mainDb | nindent 8 }}
        {{- include "baseResources.waitForRedis" (dict
            "host" (include "redis.serviceFQDN" (dict "root" $))
            "password" $.Values.redis.password) | nindent 8 }}

      containers:
        {{- include "baseResources.baseContainer" (dict "root" $ "vals" .) | indent 8 }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-env" $.Release.Name }}
            - secretRef:
                name: {{ printf "%s-secret" $.Release.Name }}

          env:
          - name: SERVICE_TYPE
            value: "worker"

          volumeMounts:
            - name: flask-temp
              mountPath: /app/temp_audio

      volumes:
        - name: flask-temp
          emptyDir: {}
{{- end }}