apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print .Release.Name "-data" | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- with .Values.storage.data.volumeName }}
  volumeName: {{ . | quote }}
{{- end }}