{{- define "mariadb.grant" -}}
{{- $root := .root | default . }}
{{- $vals := .vals | default $root.Values }}
{{- $fullname := include "mariadb.grantName" (dict "root" $root "vals" $vals) }}

apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ $fullname | quote }}
  labels:
    {{- include "common.labels" $root | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  mariaDbRef:
    name: {{ $vals.instanceName | quote }}
    namespace: {{ $vals.namespace | quote }}
  privileges:
    - "ALL"
  database: {{ $vals.name | quote }}
  table: "*"
  username: {{ $vals.username | quote }}
  host: "%"
  grantOption: false
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
{{- end }}