apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ printf "%s-db-grant" (include "mariadb.fullname" .) | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  mariaDbRef:
    name: "{{ .Values.instanceName }}"
    namespace: "{{ .Values.namespace }}"
  privileges:
    - "ALL"
  database: "{{ .Values.name }}"
  table: "*"
  username: "{{ .Values.username }}"
  host: "%"
  grantOption: false
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
