apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ printf "%s-db-user" (include "mariadb.fullname" .) | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  name: "{{ .Values.username }}"
  mariaDbRef:
    name: "{{ .Values.instanceName }}"
    namespace: "{{ .Values.namespace }}"
  passwordSecretKeyRef:
    name: "{{ .Release.Name }}-secret"
    key: "{{ .Values.passwordKey }}"
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
