---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: db-crowdsec
  namespace: crowdsec
spec:
  storage:
    size: 3Gi
  replicas: 1
  service:
    type: ClusterIP
    sessionAffinity: None
  tls:
    enabled: true
    required: false
    serverCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
    clientCertIssuerRef:
      name: cluster-ca
      kind: ClusterIssuer
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  name: crowdsec
  mariaDbRef:
    name: db-crowdsec
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: crowdsec-user
  namespace: crowdsec
spec:
  name: crowdsec-user
  mariaDbRef:
    name: db-crowdsec
  passwordSecretKeyRef:
    name: crowdsec-secret
    key: DB_PASSWD
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: crowdsec-user-grant
  namespace: crowdsec
spec:
  mariaDbRef:
    name: db-crowdsec
  privileges:
    - "ALL"
  database: crowdsec
  table: "*"
  username: crowdsec-user
  host: "%"
  grantOption: false
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
